; Listing generated by Microsoft (R) Optimizing Compiler Version 19.36.32534.0 

include listing.inc

INCLUDELIB OLDNAMES

PUBLIC	??_C@_0P@CEJPOEEF@Example?5Canvas@		; `string'
PUBLIC	??_C@_0L@DCCGFMBN@Error?3?5?$CFs?6@		; `string'
PUBLIC	??_C@_01HIHLOKLC@1@				; `string'
PUBLIC	??_C@_0BA@JCFIKKMK@SDL_IME_SHOW_UI@		; `string'
PUBLIC	??_C@_0N@DDOGMLBE@Photo?5Studio@		; `string'
PUBLIC	??_C@_0BP@BFEIMJMJ@Error?3?5SDL_CreateWindow?$CI?$CJ?3?5?$CFs?6@ ; `string'
PUBLIC	??_C@_0P@JLOCEAMK@OpenGL?5loaded?6@		; `string'
PUBLIC	??_C@_0O@BLOPLMMI@Vendor?3?5?5?5?$CFs?6@	; `string'
PUBLIC	??_C@_0O@IPGAJLBD@Renderer?3?5?$CFs?6@		; `string'
PUBLIC	??_C@_0O@NHGDCGCA@Version?3?5?5?$CFs?6@		; `string'
PUBLIC	??_C@_06JNNJGBCL@1?490?45@			; `string'
PUBLIC	??_C@_0BJ@HCOBDBIG@Fonts?1Roboto?9Regular?4ttf@	; `string'
PUBLIC	??_C@_0P@IHLBBLJK@DockSpace?5Demo@		; `string'
PUBLIC	??_C@_0M@MOJOFFHL@MyDockSpace@			; `string'
PUBLIC	??_C@_0L@KOOGALIH@Properties@			; `string'
PUBLIC	??_C@_09MELPKEIH@Title?5Bar@			; `string'
PUBLIC	??_C@_04PBAHLACE@File@				; `string'
PUBLIC	??_C@_06CPMDDACM@Ctrl?$CLN@			; `string'
PUBLIC	??_C@_0M@BKCCDHAN@New?5project@			; `string'
PUBLIC	??_C@_06NAKPFMDA@Ctrl?$CLS@			; `string'
PUBLIC	??_C@_04INACKGJP@Save@				; `string'
PUBLIC	??_C@_0N@CGJKLENG@Shift?$CLCtrl?$CLS@		; `string'
PUBLIC	??_C@_07NCJKBBP@Save?5as@			; `string'
PUBLIC	??_C@_04BBNPPDNC@Edit@				; `string'
PUBLIC	??_C@_06BGNOHHJ@Ctrl?$CLZ@			; `string'
PUBLIC	??_C@_04LPGMNMPN@Undo@				; `string'
PUBLIC	??_C@_0N@HANJOMON@Ctrl?$CLShift?$CLZ@		; `string'
PUBLIC	??_C@_04NKENIHOM@Redo@				; `string'
PUBLIC	??_C@_05NBEAGECF@Image@				; `string'
PUBLIC	??_C@_05NHNHDHBP@Layer@				; `string'
PUBLIC	??_C@_06BNPFFCKO@Ctrl?$CLL@			; `string'
PUBLIC	??_C@_09HNJMKJBB@New?5layer@			; `string'
PUBLIC	??_C@_04KOACHJEN@Type@				; `string'
PUBLIC	??_C@_06HJGPBJLE@Select@			; `string'
PUBLIC	??_C@_06IBDJIBGI@Filter@			; `string'
PUBLIC	??_C@_04OGMCGMPK@View@				; `string'
PUBLIC	??_C@_0N@LIAAGGOF@Ctrl?$CLShift?$CLR@		; `string'
PUBLIC	??_C@_0L@NDBEAOBP@Reset?5view@			; `string'
PUBLIC	??_C@_06BKKJGDHO@Window@			; `string'
PUBLIC	??_C@_04DDFEFHOJ@Help@				; `string'
PUBLIC	??_C@_0M@GEIJOAJB@New?5Canvas?5@		; `string'
PUBLIC	??_R1A@?0A@EA@?$_Ref_count_obj2@VCanvas@@@std@@8 ; std::_Ref_count_obj2<Canvas>::`RTTI Base Class Descriptor at (0,-1,0,64)'
PUBLIC	?_OptionsStorage@?1??__local_stdio_printf_options@@9@4_KA ; `__local_stdio_printf_options'::`2'::_OptionsStorage
PUBLIC	??_R3?$_Ref_count_obj2@VCanvas@@@std@@8		; std::_Ref_count_obj2<Canvas>::`RTTI Class Hierarchy Descriptor'
PUBLIC	??_7?$_Ref_count_obj2@VCanvas@@@std@@6B@	; std::_Ref_count_obj2<Canvas>::`vftable'
PUBLIC	?m_GLContext@Application@@0PEAXEA		; Application::m_GLContext
PUBLIC	??_R0?AV?$_Ref_count_obj2@VCanvas@@@std@@@8	; std::_Ref_count_obj2<Canvas> `RTTI Type Descriptor'
PUBLIC	??_R4?$_Ref_count_obj2@VCanvas@@@std@@6B@	; std::_Ref_count_obj2<Canvas>::`RTTI Complete Object Locator'
PUBLIC	??_R2?$_Ref_count_obj2@VCanvas@@@std@@8		; std::_Ref_count_obj2<Canvas>::`RTTI Base Class Array'
EXTRN	__imp_SDL_GetWindowSize:PROC
EXTRN	__imp_SDL_CreateWindow:PROC
EXTRN	__imp_SDL_GL_SetSwapInterval:PROC
EXTRN	__imp_SDL_PollEvent:PROC
EXTRN	__imp_SDL_GL_CreateContext:PROC
EXTRN	__imp___stdio_common_vfprintf:PROC
EXTRN	__imp_SDL_GL_SetAttribute:PROC
EXTRN	__imp_SDL_GL_GetProcAddress:PROC
EXTRN	__imp_SDL_GetWindowID:PROC
EXTRN	__imp_SDL_GetWindowWMInfo:PROC
EXTRN	__imp_SDL_Quit:PROC
EXTRN	__imp_SDL_SetHint:PROC
EXTRN	__imp_SDL_AddEventWatch:PROC
EXTRN	__imp_SDL_DestroyWindow:PROC
EXTRN	__imp_SDL_Init:PROC
EXTRN	__imp___acrt_iob_func:PROC
EXTRN	__imp_SDL_GL_MakeCurrent:PROC
EXTRN	__imp_DwmSetWindowAttribute:PROC
EXTRN	__imp_SDL_GL_DeleteContext:PROC
EXTRN	__imp_SDL_GL_SwapWindow:PROC
EXTRN	__imp_SDL_GL_GetCurrentContext:PROC
;	COMDAT ?_OptionsStorage@?1??__local_stdio_printf_options@@9@4_KA
_BSS	SEGMENT
?_OptionsStorage@?1??__local_stdio_printf_options@@9@4_KA DQ 01H DUP (?) ; `__local_stdio_printf_options'::`2'::_OptionsStorage
_BSS	ENDS
;	COMDAT ?m_GLContext@Application@@0PEAXEA
_BSS	SEGMENT
?m_GLContext@Application@@0PEAXEA DQ 01H DUP (?)	; Application::m_GLContext
_BSS	ENDS
