; Listing generated by Microsoft (R) Optimizing Compiler Version 19.36.32535.0 

include listing.inc

INCLUDELIB OLDNAMES

PUBLIC	??_C@_04CHADEDPO@view@				; `string'
PUBLIC	??_C@_0L@PPHAJBEH@projection@			; `string'
PUBLIC	??_C@_05PDOBBJNA@Color@				; `string'
PUBLIC	??_C@_05NCCFOPHA@model@				; `string'
PUBLIC	??_C@_0L@CKCKKFCJ@Brush?5tool@			; `string'
EXTRN	_Init_thread_header:PROC
EXTRN	_Init_thread_footer:PROC
EXTRN	_Init_thread_epoch:DWORD
;	COMDAT ?flags@?1??DrawPaintbrushMenu@Brush@@QEAAXXZ@4HA
_BSS	SEGMENT
?flags@?1??DrawPaintbrushMenu@Brush@@QEAAXXZ@4HA DD 01H DUP (?) ; `Brush::DrawPaintbrushMenu'::`2'::flags
_BSS	ENDS
;	COMDAT ?Pressed@?1??DrawInterpolatedPaintbrush@Brush@@QEAAXU?$vec@$02M$0A@@glm@@M@Z@4_NA
_DATA	SEGMENT
?Pressed@?1??DrawInterpolatedPaintbrush@Brush@@QEAAXU?$vec@$02M$0A@@glm@@M@Z@4_NA DB 01H ; `Brush::DrawInterpolatedPaintbrush'::`2'::Pressed
_DATA	ENDS
;	COMDAT ??_C@_0L@CKCKKFCJ@Brush?5tool@
CONST	SEGMENT
??_C@_0L@CKCKKFCJ@Brush?5tool@ DB 'Brush tool', 00H	; `string'
CONST	ENDS
;	COMDAT ??_C@_05NCCFOPHA@model@
CONST	SEGMENT
??_C@_05NCCFOPHA@model@ DB 'model', 00H			; `string'
CONST	ENDS
;	COMDAT ??_C@_05PDOBBJNA@Color@
CONST	SEGMENT
??_C@_05PDOBBJNA@Color@ DB 'Color', 00H			; `string'
CONST	ENDS
;	COMDAT ??_C@_0L@PPHAJBEH@projection@
CONST	SEGMENT
??_C@_0L@PPHAJBEH@projection@ DB 'projection', 00H	; `string'
CONST	ENDS
;	COMDAT ??_C@_04CHADEDPO@view@
CONST	SEGMENT
??_C@_04CHADEDPO@view@ DB 'view', 00H			; `string'
PUBLIC	?call@?$compute_vec4_add@M$0A@$0A@@detail@glm@@SA?AU?$vec@$03M$0A@@3@AEBU43@0@Z ; glm::detail::compute_vec4_add<float,0,0>::call
PUBLIC	??$?DM$0A@@glm@@YA?AU?$vec@$02M$0A@@0@AEBU10@0@Z ; glm::operator*<float,0>
PUBLIC	??$?YM@?$vec@$03M$0A@@glm@@QEAAAEAU01@AEBU01@@Z	; glm::vec<4,float,0>::operator+=<float>
PUBLIC	?call@?$compute_vec4_mul@M$0A@$0A@@detail@glm@@SA?AU?$vec@$03M$0A@@3@AEBU43@0@Z ; glm::detail::compute_vec4_mul<float,0,0>::call
PUBLIC	?call@?$compute_dot@U?$vec@$02M$0A@@glm@@M$0A@@detail@glm@@SAMAEBU?$vec@$02M$0A@@3@0@Z ; glm::detail::compute_dot<glm::vec<3,float,0>,float,0>::call
PUBLIC	??$dot@$02M$0A@@glm@@YAMAEBU?$vec@$02M$0A@@0@0@Z ; glm::dot<3,float,0>
PUBLIC	??$?HM$0A@@glm@@YA?AU?$vec@$03M$0A@@0@AEBU10@0@Z ; glm::operator+<float,0>
PUBLIC	??$?XM@?$vec@$03M$0A@@glm@@QEAAAEAU01@M@Z	; glm::vec<4,float,0>::operator*=<float>
PUBLIC	??$?0HHHM@?$vec@$03M$0A@@glm@@QEAA@HHHM@Z	; glm::vec<4,float,0>::vec<4,float,0><int,int,int,float>
PUBLIC	??$?0HHMH@?$vec@$03M$0A@@glm@@QEAA@HHMH@Z	; glm::vec<4,float,0>::vec<4,float,0><int,int,float,int>
PUBLIC	??$?0HMHH@?$vec@$03M$0A@@glm@@QEAA@HMHH@Z	; glm::vec<4,float,0>::vec<4,float,0><int,float,int,int>
PUBLIC	??$?0MHHH@?$vec@$03M$0A@@glm@@QEAA@MHHH@Z	; glm::vec<4,float,0>::vec<4,float,0><float,int,int,int>
PUBLIC	??A?$mat@$03$03M$0A@@glm@@QEAAAEAU?$vec@$03M$0A@@1@H@Z ; glm::mat<4,4,float,0>::operator[]
PUBLIC	??A?$mat@$03$03M$0A@@glm@@QEBAAEBU?$vec@$03M$0A@@1@H@Z ; glm::mat<4,4,float,0>::operator[]
PUBLIC	??0?$vec@$03M$0A@@glm@@QEAA@M@Z			; glm::vec<4,float,0>::vec<4,float,0>
PUBLIC	??0?$vec@$03M$0A@@glm@@QEAA@MMMM@Z		; glm::vec<4,float,0>::vec<4,float,0>
PUBLIC	??0?$vec@$02M$0A@@glm@@QEAA@MMM@Z		; glm::vec<3,float,0>::vec<3,float,0>
PUBLIC	??A?$vec@$02M$0A@@glm@@QEBAAEBMH@Z		; glm::vec<3,float,0>::operator[]
PUBLIC	?call@?$compute_length@$02M$0A@$0A@@detail@glm@@SAMAEBU?$vec@$02M$0A@@3@@Z ; glm::detail::compute_length<3,float,0,0>::call
PUBLIC	??$_Construct@$00PEBD@?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@AEAAXQEBD_K@Z ; std::basic_string<char,std::char_traits<char>,std::allocator<char> >::_Construct<1,char const *>
PUBLIC	??$?0$$V@?$_Compressed_pair@V?$allocator@D@std@@V?$_String_val@U?$_Simple_types@D@std@@@2@$00@std@@QEAA@U_Zero_then_variadic_args_t@1@@Z ; std::_Compressed_pair<std::allocator<char>,std::_String_val<std::_Simple_types<char> >,1>::_Compressed_pair<std::allocator<char>,std::_String_val<std::_Simple_types<char> >,1><>
PUBLIC	??$scale@M$0A@@glm@@YA?AU?$mat@$03$03M$0A@@0@AEBU10@AEBU?$vec@$02M$0A@@0@@Z ; glm::scale<float,0>
PUBLIC	??$?0MMH@?$vec@$02M$0A@@glm@@QEAA@MMH@Z		; glm::vec<3,float,0>::vec<3,float,0><float,float,int>
PUBLIC	??$?0MMMN@?$vec@$03M$0A@@glm@@QEAA@MMMN@Z	; glm::vec<4,float,0>::vec<4,float,0><float,float,float,double>
PUBLIC	??$ortho@M@glm@@YA?AU?$mat@$03$03M$0A@@0@MMMM@Z	; glm::ortho<float>
PUBLIC	??$translate@M$0A@@glm@@YA?AU?$mat@$03$03M$0A@@0@AEBU10@AEBU?$vec@$02M$0A@@0@@Z ; glm::translate<float,0>
PUBLIC	??$?0HHH@?$vec@$02M$0A@@glm@@QEAA@HHH@Z		; glm::vec<3,float,0>::vec<3,float,0><int,int,int>
PUBLIC	??$length@$02M$0A@@glm@@YAMAEBU?$vec@$02M$0A@@0@@Z ; glm::length<3,float,0>
PUBLIC	??$?GM$0A@@glm@@YA?AU?$vec@$02M$0A@@0@AEBU10@0@Z ; glm::operator-<float,0>
PUBLIC	??$?DM$0A@@glm@@YA?AU?$vec@$03M$0A@@0@AEBU10@AEBM@Z ; glm::operator*<float,0>
PUBLIC	??0?$mat@$03$03M$0A@@glm@@QEAA@AEBM@Z		; glm::mat<4,4,float,0>::mat<4,4,float,0>
PUBLIC	??0?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@QEAA@QEBD@Z ; std::basic_string<char,std::char_traits<char>,std::allocator<char> >::basic_string<char,std::char_traits<char>,std::allocator<char> >
PUBLIC	??C?$unique_ptr@VCanvasObject@@U?$default_delete@VCanvasObject@@@std@@@std@@QEBAPEAVCanvasObject@@XZ ; std::unique_ptr<CanvasObject,std::default_delete<CanvasObject> >::operator->
PUBLIC	?DrawPaintbrushMenu@Brush@@QEAAXXZ		; Brush::DrawPaintbrushMenu
PUBLIC	?DrawPencil@Brush@@AEAAXU?$vec@$02M$0A@@glm@@M@Z ; Brush::DrawPencil
PUBLIC	?DrawInterpolatedPaintbrush@Brush@@QEAAXU?$vec@$02M$0A@@glm@@M@Z ; Brush::DrawInterpolatedPaintbrush
PUBLIC	??1Brush@@QEAA@XZ				; Brush::~Brush
PUBLIC	??0Brush@@QEAA@XZ				; Brush::Brush
PUBLIC	?sqrt@@YAMM@Z					; sqrt
;	COMDAT ?PreviousDrawnPosition@?1??DrawInterpolatedPaintbrush@Brush@@QEAAXU?$vec@$02M$0A@@glm@@M@Z@4U34@A
_BSS	SEGMENT
?PreviousDrawnPosition@?1??DrawInterpolatedPaintbrush@Brush@@QEAAXU?$vec@$02M$0A@@glm@@M@Z@4U34@A DB 0cH DUP (?) ; `Brush::DrawInterpolatedPaintbrush'::`2'::PreviousDrawnPosition
_BSS	ENDS
;	COMDAT ?$TSS1@?1??DrawInterpolatedPaintbrush@Brush@@QEAAXU?$vec@$02M$0A@@glm@@M@Z@4HA
_BSS	SEGMENT
?$TSS1@?1??DrawInterpolatedPaintbrush@Brush@@QEAAXU?$vec@$02M$0A@@glm@@M@Z@4HA DD 01H DUP (?) ; `Brush::DrawInterpolatedPaintbrush'::`2'::$TSS1
_BSS	ENDS
;	COMDAT ?$TSS0@?1??DrawInterpolatedPaintbrush@Brush@@QEAAXU?$vec@$02M$0A@@glm@@M@Z@4HA
_BSS	SEGMENT
?$TSS0@?1??DrawInterpolatedPaintbrush@Brush@@QEAAXU?$vec@$02M$0A@@glm@@M@Z@4HA DD 01H DUP (?) ; `Brush::DrawInterpolatedPaintbrush'::`2'::$TSS0
_BSS	ENDS
;	COMDAT ?PreviousPosition@?1??DrawInterpolatedPaintbrush@Brush@@QEAAXU?$vec@$02M$0A@@glm@@M@Z@4U34@A
_BSS	SEGMENT
?PreviousPosition@?1??DrawInterpolatedPaintbrush@Brush@@QEAAXU?$vec@$02M$0A@@glm@@M@Z@4U34@A DB 0cH DUP (?) ; `Brush::DrawInterpolatedPaintbrush'::`2'::PreviousPosition
_BSS	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$??$_Construct@$00PEBD@?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@AEAAXQEBD_K@Z DD imagerel $LN76@Construct
	DD	imagerel $LN76@Construct+79
	DD	imagerel $unwind$??$_Construct@$00PEBD@?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@AEAAXQEBD_K@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$0$??$_Construct@$00PEBD@?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@AEAAXQEBD_K@Z DD imagerel $LN76@Construct+79
	DD	imagerel $LN76@Construct+241
	DD	imagerel $chain$0$??$_Construct@$00PEBD@?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@AEAAXQEBD_K@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$1$??$_Construct@$00PEBD@?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@AEAAXQEBD_K@Z DD imagerel $LN76@Construct+241
	DD	imagerel $LN76@Construct+247
	DD	imagerel $chain$1$??$_Construct@$00PEBD@?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@AEAAXQEBD_K@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$2$??$_Construct@$00PEBD@?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@AEAAXQEBD_K@Z DD imagerel $LN76@Construct+247
	DD	imagerel $LN76@Construct+253
	DD	imagerel $chain$2$??$_Construct@$00PEBD@?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@AEAAXQEBD_K@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$??$scale@M$0A@@glm@@YA?AU?$mat@$03$03M$0A@@0@AEBU10@AEBU?$vec@$02M$0A@@0@@Z DD imagerel $LN98@scale
	DD	imagerel $LN98@scale+282
	DD	imagerel $unwind$??$scale@M$0A@@glm@@YA?AU?$mat@$03$03M$0A@@0@AEBU10@AEBU?$vec@$02M$0A@@0@@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$??$ortho@M@glm@@YA?AU?$mat@$03$03M$0A@@0@MMMM@Z DD imagerel $LN69@ortho
	DD	imagerel $LN69@ortho+178
	DD	imagerel $unwind$??$ortho@M@glm@@YA?AU?$mat@$03$03M$0A@@0@MMMM@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$??$translate@M$0A@@glm@@YA?AU?$mat@$03$03M$0A@@0@AEBU10@AEBU?$vec@$02M$0A@@0@@Z DD imagerel $LN140@translate
	DD	imagerel $LN140@translate+375
	DD	imagerel $unwind$??$translate@M$0A@@glm@@YA?AU?$mat@$03$03M$0A@@0@AEBU10@AEBU?$vec@$02M$0A@@0@@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$??0?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@QEAA@QEBD@Z DD imagerel $LN90@basic_stri
	DD	imagerel $LN90@basic_stri+287
	DD	imagerel $unwind$??0?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@QEAA@QEBD@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$?DrawPaintbrushMenu@Brush@@QEAAXXZ DD imagerel $LN12@DrawPaintb
	DD	imagerel $LN12@DrawPaintb+226
	DD	imagerel $unwind$?DrawPaintbrushMenu@Brush@@QEAAXXZ
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$?DrawPencil@Brush@@AEAAXU?$vec@$02M$0A@@glm@@M@Z DD imagerel $LN145@DrawPencil
	DD	imagerel $LN145@DrawPencil+363
	DD	imagerel $unwind$?DrawPencil@Brush@@AEAAXU?$vec@$02M$0A@@glm@@M@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$?DrawInterpolatedPaintbrush@Brush@@QEAAXU?$vec@$02M$0A@@glm@@M@Z DD imagerel $LN729@DrawInterp
	DD	imagerel $LN729@DrawInterp+1866
	DD	imagerel $unwind$?DrawInterpolatedPaintbrush@Brush@@QEAAXU?$vec@$02M$0A@@glm@@M@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$??1Brush@@QEAA@XZ DD imagerel $LN11@Brush
	DD	imagerel $LN11@Brush+34
	DD	imagerel $unwind$??1Brush@@QEAA@XZ
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$??0Brush@@QEAA@XZ DD imagerel $LN6@Brush
	DD	imagerel $LN6@Brush+43
	DD	imagerel $unwind$??0Brush@@QEAA@XZ
;	COMDAT xdata
xdata	SEGMENT
$unwind$??0Brush@@QEAA@XZ DQ 03002320600020601r	; 1.96423e-77
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$ip2state$??1Brush@@QEAA@XZ DW 01802H
	DB	02H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$stateUnwindMap$??1Brush@@QEAA@XZ DW 0e02H
	DD	imagerel __std_terminate
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$cppxdata$??1Brush@@QEAA@XZ DB 068H
	DD	imagerel $stateUnwindMap$??1Brush@@QEAA@XZ
	DD	imagerel $ip2state$??1Brush@@QEAA@XZ
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$??1Brush@@QEAA@XZ DQ 03002320600020619r	; 1.96423e-77
	DD	imagerel __CxxFrameHandler4
	DD	imagerel $cppxdata$??1Brush@@QEAA@XZ
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$ip2state$?DrawInterpolatedPaintbrush@Brush@@QEAAXU?$vec@$02M$0A@@glm@@M@Z DQ 0360203bd00074d12r ; 1.54076e-48
	DQ	004e8003004049900r		; 5.04381e-285
	DD	05690068H
	DW	04c02H
	DB	00H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$stateUnwindMap$?DrawInterpolatedPaintbrush@Brush@@QEAAXU?$vec@$02M$0A@@glm@@M@Z DW 0a04H
	DD	imagerel ??1?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@QEAA@XZ
	DW	03a80H
	DD	imagerel ??1?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@QEAA@XZ
	DW	0201H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$cppxdata$?DrawInterpolatedPaintbrush@Brush@@QEAAXU?$vec@$02M$0A@@glm@@M@Z DB 028H
	DD	imagerel $stateUnwindMap$?DrawInterpolatedPaintbrush@Brush@@QEAAXU?$vec@$02M$0A@@glm@@M@Z
	DD	imagerel $ip2state$?DrawInterpolatedPaintbrush@Brush@@QEAAXU?$vec@$02M$0A@@glm@@M@Z
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$?DrawInterpolatedPaintbrush@Brush@@QEAAXU?$vec@$02M$0A@@glm@@M@Z DQ 00012c84300174311r ; 2.612e-308
	DQ	00014a8330013b83br		; 2.87271e-308
	DQ	0001688290015982er		; 3.13344e-308
	DQ	00018682000177824r		; 3.39417e-308
	DQ	00032011c0039341cr		; 1.00152e-307
	DQ	06009700ae00cf00er		; 4.26329e+154
	DD	05008H
	DD	imagerel __CxxFrameHandler4
	DD	imagerel $cppxdata$?DrawInterpolatedPaintbrush@Brush@@QEAAXU?$vec@$02M$0A@@glm@@M@Z
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$ip2state$?DrawPencil@Brush@@AEAAXU?$vec@$02M$0A@@glm@@M@Z DD 0202f504H
	DW	030H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$stateUnwindMap$?DrawPencil@Brush@@AEAAXU?$vec@$02M$0A@@glm@@M@Z DW 0a02H
	DD	imagerel ??1?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@QEAA@XZ
	DB	040H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$cppxdata$?DrawPencil@Brush@@AEAAXU?$vec@$02M$0A@@glm@@M@Z DB 028H
	DD	imagerel $stateUnwindMap$?DrawPencil@Brush@@AEAAXU?$vec@$02M$0A@@glm@@M@Z
	DD	imagerel $ip2state$?DrawPencil@Brush@@AEAAXU?$vec@$02M$0A@@glm@@M@Z
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$?DrawPencil@Brush@@AEAAXU?$vec@$02M$0A@@glm@@M@Z DQ 00022010900030911r ; 5.00754e-308
	DD	03002H
	DD	imagerel __CxxFrameHandler4
	DD	imagerel $cppxdata$?DrawPencil@Brush@@AEAAXU?$vec@$02M$0A@@glm@@M@Z
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$?DrawPaintbrushMenu@Brush@@QEAAXXZ DQ 03002b20600021519r ; 2.01821e-77
	DD	imagerel __GSHandlerCheck
	DD	050H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$??0?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@QEAA@QEBD@Z DQ 0000b541200081201r ; 1.57541e-308
	DQ	0e00e3212000a3412r		; -5.06071e+154
	DD	0600b700cH
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$??$translate@M$0A@@glm@@YA?AU?$mat@$03$03M$0A@@0@AEBU10@AEBU?$vec@$02M$0A@@0@@Z DQ 00001b86e000d6e01r ; 2.39255e-309
	DQ	0000398400002a849r		; 4.99908e-309
	DQ	00005782d00048836r		; 7.60619e-309
	DQ	00000e20700066822r		; 1.22785e-309
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$??$ortho@M@glm@@YA?AU?$mat@$03$03M$0A@@0@MMMM@Z DQ 00000780f00050f01r ; 6.52195e-310
	DQ	00000420400016809r		; 3.58617e-310
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$??$scale@M$0A@@glm@@YA?AU?$mat@$03$03M$0A@@0@AEBU10@AEBU?$vec@$02M$0A@@0@@Z DQ 00001681400031401r ; 1.95606e-309
	DD	04204H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$chain$2$??$_Construct@$00PEBD@?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@AEAAXQEBD_K@Z DQ 00004640000020021r ; 6.10592e-309
	DD	imagerel $LN76@Construct
	DD	imagerel $LN76@Construct+79
	DD	imagerel $unwind$??$_Construct@$00PEBD@?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@AEAAXQEBD_K@Z
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$chain$1$??$_Construct@$00PEBD@?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@AEAAXQEBD_K@Z DD 021H
	DD	imagerel $LN76@Construct
	DD	imagerel $LN76@Construct+79
	DD	imagerel $unwind$??$_Construct@$00PEBD@?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@AEAAXQEBD_K@Z
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$chain$0$??$_Construct@$00PEBD@?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@AEAAXQEBD_K@Z DQ 00004640500020521r ; 6.10602e-309
	DD	imagerel $LN76@Construct
	DD	imagerel $LN76@Construct+79
	DD	imagerel $unwind$??$_Construct@$00PEBD@?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@AEAAXQEBD_K@Z
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$??$_Construct@$00PEBD@?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@AEAAXQEBD_K@Z DQ 0e006420a00050a01r ; -3.73038e+154
	DQ	00000300250037004r		; 2.608e-310
END
