; Listing generated by Microsoft (R) Optimizing Compiler Version 19.36.32534.0 

include listing.inc

INCLUDELIB OLDNAMES

PUBLIC	??_C@_05PDOBBJNA@Color@				; `string'
PUBLIC	??_C@_0L@CKCKKFCJ@Brush?5tool@			; `string'
EXTRN	_Init_thread_header:PROC
EXTRN	_Init_thread_footer:PROC
EXTRN	_Init_thread_epoch:DWORD
;	COMDAT ?flags@?1??DrawPaintbrushMenu@Brush@@QEAAXXZ@4HA
_BSS	SEGMENT
?flags@?1??DrawPaintbrushMenu@Brush@@QEAAXXZ@4HA DD 01H DUP (?) ; `Brush::DrawPaintbrushMenu'::`2'::flags
_BSS	ENDS
