; Listing generated by Microsoft (R) Optimizing Compiler Version 19.36.32535.0 

include listing.inc

INCLUDELIB OLDNAMES

PUBLIC	??_C@_0L@MALGKGOF@Background@			; `string'
PUBLIC	??_C@_0L@NLBOBKBC@Test?5layer@			; `string'
PUBLIC	??_C@_04EEOGCCFB@?4png@				; `string'
PUBLIC	??_C@_07OGIHEKIC@Images?1@			; `string'
PUBLIC	?m_CanvasScale@CanvasData@@2MA			; CanvasData::m_CanvasScale
PUBLIC	?m_ActiveCanvas@CanvasData@@2HA			; CanvasData::m_ActiveCanvas
PUBLIC	?m_CanvasOffset@CanvasData@@2U?$vec@$01M$0A@@glm@@A ; CanvasData::m_CanvasOffset
PUBLIC	?m_CanvasMultiplier@CanvasData@@2MA		; CanvasData::m_CanvasMultiplier
PUBLIC	?m_CanvasHovered@CanvasData@@2_NA		; CanvasData::m_CanvasHovered
PUBLIC	?m_CanvasFocused@CanvasData@@2_NA		; CanvasData::m_CanvasFocused
PUBLIC	?m_ViewportSize@CanvasData@@2U?$vec@$01M$0A@@glm@@A ; CanvasData::m_ViewportSize
EXTRN	__imp_?good@ios_base@std@@QEBA_NXZ:PROC
EXTRN	__imp_?flags@ios_base@std@@QEBAHXZ:PROC
EXTRN	__imp_?width@ios_base@std@@QEBA_JXZ:PROC
EXTRN	__imp_?width@ios_base@std@@QEAA_J_J@Z:PROC
EXTRN	__imp_?sputc@?$basic_streambuf@DU?$char_traits@D@std@@@std@@QEAAHD@Z:PROC
EXTRN	__imp_?fill@?$basic_ios@DU?$char_traits@D@std@@@std@@QEBADXZ:PROC
EXTRN	__imp_?rdbuf@?$basic_ios@DU?$char_traits@D@std@@@std@@QEBAPEAV?$basic_streambuf@DU?$char_traits@D@std@@@2@XZ:PROC
EXTRN	__imp_?setstate@?$basic_ios@DU?$char_traits@D@std@@@std@@QEAAXH_N@Z:PROC
EXTRN	__imp_?sputn@?$basic_streambuf@DU?$char_traits@D@std@@@std@@QEAA_JPEBD_J@Z:PROC
EXTRN	__imp_?flush@?$basic_ostream@DU?$char_traits@D@std@@@std@@QEAAAEAV12@XZ:PROC
EXTRN	__imp_?_Osfx@?$basic_ostream@DU?$char_traits@D@std@@@std@@QEAAXXZ:PROC
EXTRN	__imp_?tie@?$basic_ios@DU?$char_traits@D@std@@@std@@QEBAPEAV?$basic_ostream@DU?$char_traits@D@std@@@2@XZ:PROC
EXTRN	__imp_IMG_SavePNG:PROC
EXTRN	__imp_SDL_FreeSurface:PROC
EXTRN	__imp_SDL_GetGlobalMouseState:PROC
EXTRN	__imp_SDL_CreateRGBSurfaceWithFormatFrom:PROC
EXTRN	__imp_SDL_GetError:PROC
EXTRN	__imp_?cout@std@@3V?$basic_ostream@DU?$char_traits@D@std@@@1@A:BYTE
EXTRN	__imp_?uncaught_exceptions@std@@YAHXZ:PROC
;	COMDAT ?m_CanvasOffset@CanvasData@@2U?$vec@$01M$0A@@glm@@A
_BSS	SEGMENT
?m_CanvasOffset@CanvasData@@2U?$vec@$01M$0A@@glm@@A DQ 01H DUP (?) ; CanvasData::m_CanvasOffset
_BSS	ENDS
;	COMDAT ?m_CanvasHovered@CanvasData@@2_NA
_BSS	SEGMENT
?m_CanvasHovered@CanvasData@@2_NA DB 01H DUP (?)	; CanvasData::m_CanvasHovered
_BSS	ENDS
;	COMDAT ?m_CanvasFocused@CanvasData@@2_NA
_BSS	SEGMENT
?m_CanvasFocused@CanvasData@@2_NA DB 01H DUP (?)	; CanvasData::m_CanvasFocused
_BSS	ENDS
;	COMDAT ?m_ViewportSize@CanvasData@@2U?$vec@$01M$0A@@glm@@A
_BSS	SEGMENT
?m_ViewportSize@CanvasData@@2U?$vec@$01M$0A@@glm@@A DQ 01H DUP (?) ; CanvasData::m_ViewportSize
_BSS	ENDS
;	COMDAT ?m_CanvasMultiplier@CanvasData@@2MA
_DATA	SEGMENT
?m_CanvasMultiplier@CanvasData@@2MA DD 03f800000r ; 1	; CanvasData::m_CanvasMultiplier
_DATA	ENDS
;	COMDAT ?m_ActiveCanvas@CanvasData@@2HA
_DATA	SEGMENT
?m_ActiveCanvas@CanvasData@@2HA DD 0ffffff9cH		; CanvasData::m_ActiveCanvas
_DATA	ENDS
;	COMDAT ?m_CanvasScale@CanvasData@@2MA
_DATA	SEGMENT
?m_CanvasScale@CanvasData@@2MA DD 03f800000r	; 1	; CanvasData::m_CanvasScale
_DATA	ENDS
;	COMDAT ??_C@_07OGIHEKIC@Images?1@
CONST	SEGMENT
??_C@_07OGIHEKIC@Images?1@ DB 'Images/', 00H		; `string'
CONST	ENDS
;	COMDAT ??_C@_04EEOGCCFB@?4png@
CONST	SEGMENT
??_C@_04EEOGCCFB@?4png@ DB '.png', 00H			; `string'
CONST	ENDS
;	COMDAT ??_C@_0L@NLBOBKBC@Test?5layer@
CONST	SEGMENT
??_C@_0L@NLBOBKBC@Test?5layer@ DB 'Test layer', 00H	; `string'
CONST	ENDS
;	COMDAT ??_C@_0L@MALGKGOF@Background@
CONST	SEGMENT
??_C@_0L@MALGKGOF@Background@ DB 'Background', 00H	; `string'
PUBLIC	??0_Sentry_base@?$basic_ostream@DU?$char_traits@D@std@@@std@@QEAA@AEAV12@@Z ; std::basic_ostream<char,std::char_traits<char> >::_Sentry_base::_Sentry_base
PUBLIC	??1_Sentry_base@?$basic_ostream@DU?$char_traits@D@std@@@std@@QEAA@XZ ; std::basic_ostream<char,std::char_traits<char> >::_Sentry_base::~_Sentry_base
PUBLIC	??0sentry@?$basic_ostream@DU?$char_traits@D@std@@@std@@QEAA@AEAV12@@Z ; std::basic_ostream<char,std::char_traits<char> >::sentry::sentry
PUBLIC	??1sentry@?$basic_ostream@DU?$char_traits@D@std@@@std@@QEAA@XZ ; std::basic_ostream<char,std::char_traits<char> >::sentry::~sentry
PUBLIC	??Bsentry@?$basic_ostream@DU?$char_traits@D@std@@@std@@QEBA_NXZ ; std::basic_ostream<char,std::char_traits<char> >::sentry::operator bool
PUBLIC	??$?HDU?$char_traits@D@std@@V?$allocator@D@1@@std@@YA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@0@$$QEAV10@QEBD@Z ; std::operator+<char,std::char_traits<char>,std::allocator<char> >
PUBLIC	??$?6U?$char_traits@D@std@@@std@@YAAEAV?$basic_ostream@DU?$char_traits@D@std@@@0@AEAV10@PEBD@Z ; std::operator<<<std::char_traits<char> >
PUBLIC	??$?KM$0A@@glm@@YA?AU?$vec@$02M$0A@@0@AEBU10@0@Z ; glm::operator/<float,0>
PUBLIC	??$?DM$0A@@glm@@YA?AU?$vec@$02M$0A@@0@AEBU10@M@Z ; glm::operator*<float,0>
PUBLIC	??0?$vec@$01H$0A@@glm@@QEAA@HH@Z		; glm::vec<2,int,0>::vec<2,int,0>
PUBLIC	?eq_int_type@?$_Narrow_char_traits@DH@std@@SA_NAEBH0@Z ; std::_Narrow_char_traits<char,int>::eq_int_type
PUBLIC	?eof@?$_Narrow_char_traits@DH@std@@SAHXZ	; std::_Narrow_char_traits<char,int>::eof
PUBLIC	??C?$unique_ptr@VShader@@U?$default_delete@VShader@@@std@@@std@@QEBAPEAVShader@@XZ ; std::unique_ptr<Shader,std::default_delete<Shader> >::operator->
PUBLIC	?SaveAs@Canvas@@QEAAXXZ				; Canvas::SaveAs
PUBLIC	?MouseInCanvas@Canvas@@QEAA_NXZ			; Canvas::MouseInCanvas
PUBLIC	?GetCanvasMousePosition@Canvas@@QEAA?AU?$vec@$02M$0A@@glm@@XZ ; Canvas::GetCanvasMousePosition
PUBLIC	?DrawCanvas@Canvas@@QEAAXXZ			; Canvas::DrawCanvas
PUBLIC	?SetActive@Canvas@@QEAAXXZ			; Canvas::SetActive
PUBLIC	??1Canvas@@QEAA@XZ				; Canvas::~Canvas
PUBLIC	??0Canvas@@QEAA@AEAVTools@@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@U?$vec@$01M$0A@@glm@@H@Z ; Canvas::Canvas
;	COMDAT pdata
pdata	SEGMENT
$pdata$??0_Sentry_base@?$basic_ostream@DU?$char_traits@D@std@@@std@@QEAA@AEAV12@@Z DD imagerel $LN11@Sentry_bas
	DD	imagerel $LN11@Sentry_bas+44
	DD	imagerel $unwind$??0_Sentry_base@?$basic_ostream@DU?$char_traits@D@std@@@std@@QEAA@AEAV12@@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$??1_Sentry_base@?$basic_ostream@DU?$char_traits@D@std@@@std@@QEAA@XZ DD imagerel $LN9@Sentry_bas
	DD	imagerel $LN9@Sentry_bas+36
	DD	imagerel $unwind$??1_Sentry_base@?$basic_ostream@DU?$char_traits@D@std@@@std@@QEAA@XZ
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$??0sentry@?$basic_ostream@DU?$char_traits@D@std@@@std@@QEAA@AEAV12@@Z DD imagerel $LN18@sentry
	DD	imagerel $LN18@sentry+133
	DD	imagerel $unwind$??0sentry@?$basic_ostream@DU?$char_traits@D@std@@@std@@QEAA@AEAV12@@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$??1sentry@?$basic_ostream@DU?$char_traits@D@std@@@std@@QEAA@XZ DD imagerel $LN14@sentry
	DD	imagerel $LN14@sentry+62
	DD	imagerel $unwind$??1sentry@?$basic_ostream@DU?$char_traits@D@std@@@std@@QEAA@XZ
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$??$?HDU?$char_traits@D@std@@V?$allocator@D@1@@std@@YA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@0@$$QEAV10@QEBD@Z DD imagerel $LN47@operator
	DD	imagerel $LN47@operator+94
	DD	imagerel $unwind$??$?HDU?$char_traits@D@std@@V?$allocator@D@1@@std@@YA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@0@$$QEAV10@QEBD@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$??$?6U?$char_traits@D@std@@@std@@YAAEAV?$basic_ostream@DU?$char_traits@D@std@@@0@AEAV10@PEBD@Z DD imagerel $LN105@operator
	DD	imagerel $LN105@operator+461
	DD	imagerel $unwind$??$?6U?$char_traits@D@std@@@std@@YAAEAV?$basic_ostream@DU?$char_traits@D@std@@@0@AEAV10@PEBD@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$?catch$17@?0???$?6U?$char_traits@D@std@@@std@@YAAEAV?$basic_ostream@DU?$char_traits@D@std@@@0@AEAV10@PEBD@Z@4HA DD imagerel ?catch$17@?0???$?6U?$char_traits@D@std@@@std@@YAAEAV?$basic_ostream@DU?$char_traits@D@std@@@0@AEAV10@PEBD@Z@4HA
	DD	imagerel ?catch$17@?0???$?6U?$char_traits@D@std@@@std@@YAAEAV?$basic_ostream@DU?$char_traits@D@std@@@0@AEAV10@PEBD@Z@4HA+59
	DD	imagerel $unwind$?catch$17@?0???$?6U?$char_traits@D@std@@@std@@YAAEAV?$basic_ostream@DU?$char_traits@D@std@@@0@AEAV10@PEBD@Z@4HA
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$?SaveAs@Canvas@@QEAAXXZ DD imagerel $LN134@SaveAs
	DD	imagerel $LN134@SaveAs+507
	DD	imagerel $unwind$?SaveAs@Canvas@@QEAAXXZ
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$?MouseInCanvas@Canvas@@QEAA_NXZ DD imagerel $LN29@MouseInCan
	DD	imagerel $LN29@MouseInCan+237
	DD	imagerel $unwind$?MouseInCanvas@Canvas@@QEAA_NXZ
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$?GetCanvasMousePosition@Canvas@@QEAA?AU?$vec@$02M$0A@@glm@@XZ DD imagerel $LN26@GetCanvasM
	DD	imagerel $LN26@GetCanvasM+346
	DD	imagerel $unwind$?GetCanvasMousePosition@Canvas@@QEAA?AU?$vec@$02M$0A@@glm@@XZ
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$?DrawCanvas@Canvas@@QEAAXXZ DD imagerel $LN1834@DrawCanvas
	DD	imagerel $LN1834@DrawCanvas+5547
	DD	imagerel $unwind$?DrawCanvas@Canvas@@QEAAXXZ
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$?SetActive@Canvas@@QEAAXXZ DD imagerel $LN45@SetActive
	DD	imagerel $LN45@SetActive+243
	DD	imagerel $unwind$?SetActive@Canvas@@QEAAXXZ
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$??1Canvas@@QEAA@XZ DD imagerel $LN47@Canvas
	DD	imagerel $LN47@Canvas+169
	DD	imagerel $unwind$??1Canvas@@QEAA@XZ
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$??0Canvas@@QEAA@AEAVTools@@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@U?$vec@$01M$0A@@glm@@H@Z DD imagerel $LN101@Canvas
	DD	imagerel $LN101@Canvas+967
	DD	imagerel $unwind$??0Canvas@@QEAA@AEAVTools@@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@U?$vec@$01M$0A@@glm@@H@Z
;	COMDAT xdata
xdata	SEGMENT
$ip2state$??0Canvas@@QEAA@AEAVTools@@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@U?$vec@$01M$0A@@glm@@H@Z DQ 0082806260402850ar ; 2.27373e-269
	DD	099d0a2cH
	DB	00H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$stateUnwindMap$??0Canvas@@QEAA@AEAVTools@@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@U?$vec@$01M$0A@@glm@@H@Z DW 0c0aH
	DD	imagerel ??1?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@QEAA@XZ
	DW	034d0H
	DD	imagerel ??1LayerManager@@QEAA@XZ
	DW	03680H
	DD	imagerel ?dtor$2@?0???0Canvas@@QEAA@AEAVTools@@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@U?$vec@$01M$0A@@glm@@H@Z@4HA
	DB	02eH
	DD	imagerel ?dtor$3@?0???0Canvas@@QEAA@AEAVTools@@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@U?$vec@$01M$0A@@glm@@H@Z@4HA
	DB	02eH
	DD	imagerel ?dtor$4@?0???0Canvas@@QEAA@AEAVTools@@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@U?$vec@$01M$0A@@glm@@H@Z@4HA
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$cppxdata$??0Canvas@@QEAA@AEAVTools@@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@U?$vec@$01M$0A@@glm@@H@Z DB 028H
	DD	imagerel $stateUnwindMap$??0Canvas@@QEAA@AEAVTools@@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@U?$vec@$01M$0A@@glm@@H@Z
	DD	imagerel $ip2state$??0Canvas@@QEAA@AEAVTools@@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@U?$vec@$01M$0A@@glm@@H@Z
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$??0Canvas@@QEAA@AEAVTools@@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@U?$vec@$01M$0A@@glm@@H@Z DQ 000088827000f3619r ; 1.1865e-308
	DQ	0000a681d00097822r		; 1.44723e-308
	DQ	0e00ff01100160118r		; -5.35269e+154
	DQ	05009600a700bc00dr		; 3.6728e+77
	DD	03008H
	DD	imagerel __GSHandlerCheck_EH4
	DD	imagerel $cppxdata$??0Canvas@@QEAA@AEAVTools@@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@U?$vec@$01M$0A@@glm@@H@Z
	DD	072H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$??1Canvas@@QEAA@XZ DQ 03002320600020601r ; 1.96423e-77
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$?SetActive@Canvas@@QEAAXXZ DQ 00000681d00031d01r ; 5.65576e-310
	DD	02204H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$ip2state$?DrawCanvas@Canvas@@QEAAXXZ DQ 0460214d10004c92ar ; 1.79069e+29
	DQ	0053d003004038500r		; 1.95026e-283
	DQ	0004c080685003806r		; 3.11859e-307
	DQ	00c03e900300a0391r		; 8.69017e-251
	DQ	08500460e07650038r		; -1.36798e-284
	DQ	03812051500301003r		; 1.32389e-38
	DD	01402e500H
	DW	07aH
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$stateUnwindMap$?DrawCanvas@Canvas@@QEAAXXZ DW 0a14H
	DD	imagerel ??1?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@QEAA@XZ
	DW	05a1H
	DB	042H
	DD	imagerel ??1?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@QEAA@XZ
	DW	09c1H
	DB	07aH
	DD	imagerel ??1?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@QEAA@XZ
	DW	0aae0H
	DD	imagerel ??1?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@QEAA@XZ
	DW	0621H
	DB	0e2H
	DD	imagerel ??1?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@QEAA@XZ
	DD	02350a41H
	DD	imagerel ??1?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@QEAA@XZ
	DD	02b502a1H
	DD	imagerel ??1?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@QEAA@XZ
	DD	03350521H
	DD	imagerel ??1?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@QEAA@XZ
	DD	03b50ac1H
	DD	imagerel ??1?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@QEAA@XZ
	DW	025a0H
	DB	04H
	DD	imagerel ??1?$shared_ptr@VLayer@@@std@@QEAA@XZ
	DW	01b01H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$cppxdata$?DrawCanvas@Canvas@@QEAAXXZ DB 028H
	DD	imagerel $stateUnwindMap$?DrawCanvas@Canvas@@QEAAXXZ
	DD	imagerel $ip2state$?DrawCanvas@Canvas@@QEAAXXZ
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$?DrawCanvas@Canvas@@QEAAXXZ DQ 0006ef86500217619r ; 1.37822e-306
	DQ	00070d855006fe85dr		; 1.49926e-306
	DQ	00072b8450071c84dr		; 1.66612e-306
	DQ	0007498380073a83dr		; 1.83298e-306
	DQ	00076782e00758833r		; 1.99985e-306
	DQ	000f974260077682ar		; 5.79956e-304
	DQ	000f7342600f86426r		; 5.28691e-304
	DQ	0e016f01800f00126r		; -7.68866e+154
	DQ	000005010c012d014r		; 4.3494e-310
	DD	imagerel __GSHandlerCheck_EH4
	DD	imagerel $cppxdata$?DrawCanvas@Canvas@@QEAAXXZ
	DD	06d2H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$?GetCanvasMousePosition@Canvas@@QEAA?AU?$vec@$02M$0A@@glm@@XZ DQ 000049823000c3219r ; 6.38914e-309
	DQ	0000678170005881dr		; 8.99639e-309
	DQ	00012340d00076812r		; 2.53148e-308
	DD	07006f20dH
	DD	imagerel __GSHandlerCheck
	DD	030H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$?MouseInCanvas@Canvas@@QEAA_NXZ DQ 00003981a00092919r ; 4.99828e-309
	DQ	00005780e00048814r		; 7.60553e-309
	DQ	00000e20400066809r		; 1.22779e-309
	DD	imagerel __GSHandlerCheck
	DD	028H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$ip2state$?SaveAs@Canvas@@QEAAXXZ DQ 0007202ac00021506r ; 1.60298e-306
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$stateUnwindMap$?SaveAs@Canvas@@QEAAXXZ DW 0a02H
	DD	imagerel ??1?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@QEAA@XZ
	DB	090H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$cppxdata$?SaveAs@Canvas@@QEAAXXZ DB 028H
	DD	imagerel $stateUnwindMap$?SaveAs@Canvas@@QEAAXXZ
	DD	imagerel $ip2state$?SaveAs@Canvas@@QEAAXXZ
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$?SaveAs@Canvas@@QEAAXXZ DQ 00016641200072419r ; 3.11384e-308
	DQ	00012011200153412r		; 2.50379e-308
	DD	0700bH
	DD	imagerel __GSHandlerCheck_EH4
	DD	imagerel $cppxdata$?SaveAs@Canvas@@QEAAXXZ
	DD	08aH
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$?catch$17@?0???$?6U?$char_traits@D@std@@@std@@YAAEAV?$basic_ostream@DU?$char_traits@D@std@@@0@AEAV10@PEBD@Z@4HA DQ 05006320a00020a01r ; 3.21257e+77
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$ip2state$??$?6U?$char_traits@D@std@@@std@@YAAEAV?$basic_ostream@DU?$char_traits@D@std@@@0@AEAV10@PEBD@Z DQ 0de06ba025c00d60cr ; -8.86834e+144
	DD	052004c04H
	DB	0aH
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$handlerMap$??$?6U?$char_traits@D@std@@@std@@YAAEAV?$basic_ostream@DU?$char_traits@D@std@@@0@AEAV10@PEBD@Z DW 01102H
	DB	080H
	DD	imagerel ?catch$17@?0???$?6U?$char_traits@D@std@@@std@@YAAEAV?$basic_ostream@DU?$char_traits@D@std@@@0@AEAV10@PEBD@Z@4HA
	DW	059dH
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$tryMap$??$?6U?$char_traits@D@std@@@std@@YAAEAV?$basic_ostream@DU?$char_traits@D@std@@@0@AEAV10@PEBD@Z DD 06040402H
	DD	imagerel $handlerMap$??$?6U?$char_traits@D@std@@@std@@YAAEAV?$basic_ostream@DU?$char_traits@D@std@@@0@AEAV10@PEBD@Z
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$stateUnwindMap$??$?6U?$char_traits@D@std@@@std@@YAAEAV?$basic_ostream@DU?$char_traits@D@std@@@0@AEAV10@PEBD@Z DW 0a0aH
	DD	imagerel ??1_Sentry_base@?$basic_ostream@DU?$char_traits@D@std@@@std@@QEAA@XZ
	DW	03a40H
	DD	imagerel ??1sentry@?$basic_ostream@DU?$char_traits@D@std@@@std@@QEAA@XZ
	DD	07e383040H
	DD	imagerel __std_terminate
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$cppxdata$??$?6U?$char_traits@D@std@@@std@@YAAEAV?$basic_ostream@DU?$char_traits@D@std@@@0@AEAV10@PEBD@Z DB 038H
	DD	imagerel $stateUnwindMap$??$?6U?$char_traits@D@std@@@std@@YAAEAV?$basic_ostream@DU?$char_traits@D@std@@@0@AEAV10@PEBD@Z
	DD	imagerel $tryMap$??$?6U?$char_traits@D@std@@@std@@YAAEAV?$basic_ostream@DU?$char_traits@D@std@@@0@AEAV10@PEBD@Z
	DD	imagerel $ip2state$??$?6U?$char_traits@D@std@@@std@@YAAEAV?$basic_ostream@DU?$char_traits@D@std@@@0@AEAV10@PEBD@Z
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$??$?6U?$char_traits@D@std@@@std@@YAAEAV?$basic_ostream@DU?$char_traits@D@std@@@0@AEAV10@PEBD@Z DQ 0000d341600081619r ; 1.83617e-308
	DQ	0c00ee010f0125216r		; -3.85941
	DD	0600b700cH
	DD	imagerel __CxxFrameHandler4
	DD	imagerel $cppxdata$??$?6U?$char_traits@D@std@@@std@@YAAEAV?$basic_ostream@DU?$char_traits@D@std@@@0@AEAV10@PEBD@Z
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$??$?HDU?$char_traits@D@std@@V?$allocator@D@1@@std@@YA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@0@$$QEAV10@QEBD@Z DQ 00008340a00040a01r ; 1.14081e-308
	DD	07006520aH
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$ip2state$??1sentry@?$basic_ostream@DU?$char_traits@D@std@@@std@@QEAA@XZ DW 06802H
	DB	02H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$stateUnwindMap$??1sentry@?$basic_ostream@DU?$char_traits@D@std@@@std@@QEAA@XZ DW 0e02H
	DD	imagerel __std_terminate
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$cppxdata$??1sentry@?$basic_ostream@DU?$char_traits@D@std@@@std@@QEAA@XZ DB 068H
	DD	imagerel $stateUnwindMap$??1sentry@?$basic_ostream@DU?$char_traits@D@std@@@std@@QEAA@XZ
	DD	imagerel $ip2state$??1sentry@?$basic_ostream@DU?$char_traits@D@std@@@std@@QEAA@XZ
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$??1sentry@?$basic_ostream@DU?$char_traits@D@std@@@std@@QEAA@XZ DQ 03002320600020619r ; 1.96423e-77
	DD	imagerel __CxxFrameHandler4
	DD	imagerel $cppxdata$??1sentry@?$basic_ostream@DU?$char_traits@D@std@@@std@@QEAA@XZ
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$ip2state$??0sentry@?$basic_ostream@DU?$char_traits@D@std@@@std@@QEAA@AEAV12@@Z DD 05c005804H
	DB	02H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$stateUnwindMap$??0sentry@?$basic_ostream@DU?$char_traits@D@std@@@std@@QEAA@AEAV12@@Z DW 0c02H
	DD	imagerel ??1_Sentry_base@?$basic_ostream@DU?$char_traits@D@std@@@std@@QEAA@XZ
	DB	060H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$cppxdata$??0sentry@?$basic_ostream@DU?$char_traits@D@std@@@std@@QEAA@AEAV12@@Z DB 028H
	DD	imagerel $stateUnwindMap$??0sentry@?$basic_ostream@DU?$char_traits@D@std@@@std@@QEAA@AEAV12@@Z
	DD	imagerel $ip2state$??0sentry@?$basic_ostream@DU?$char_traits@D@std@@@std@@QEAA@AEAV12@@Z
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$??0sentry@?$basic_ostream@DU?$char_traits@D@std@@@std@@QEAA@AEAV12@@Z DQ 00007340f00040f11r ; 1.00175e-308
	DD	0700b320fH
	DD	imagerel __CxxFrameHandler4
	DD	imagerel $cppxdata$??0sentry@?$basic_ostream@DU?$char_traits@D@std@@@std@@QEAA@AEAV12@@Z
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$ip2state$??1_Sentry_base@?$basic_ostream@DU?$char_traits@D@std@@@std@@QEAA@XZ DW 03602H
	DB	00H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$cppxdata$??1_Sentry_base@?$basic_ostream@DU?$char_traits@D@std@@@std@@QEAA@XZ DB 060H
	DD	imagerel $ip2state$??1_Sentry_base@?$basic_ostream@DU?$char_traits@D@std@@@std@@QEAA@XZ
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$??1_Sentry_base@?$basic_ostream@DU?$char_traits@D@std@@@std@@QEAA@XZ DQ 00000420400010419r ; 3.58617e-310
	DD	imagerel __CxxFrameHandler4
	DD	imagerel $cppxdata$??1_Sentry_base@?$basic_ostream@DU?$char_traits@D@std@@@std@@QEAA@XZ
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$??0_Sentry_base@?$basic_ostream@DU?$char_traits@D@std@@@std@@QEAA@AEAV12@@Z DQ 03002320600020601r ; 1.96423e-77
END
