; Listing generated by Microsoft (R) Optimizing Compiler Version 19.32.31332.0 

include listing.inc

INCLUDELIB OLDNAMES

PUBLIC	??_C@_0M@HMCLOBBL@Eraser?5tool@			; `string'
PUBLIC	??_C@_02NJPGOMH@?$CFf@				; `string'
PUBLIC	??_C@_04EBKMHHBE@Size@				; `string'
;	COMDAT ?flags@?1??DrawEraserMenu@Eraser@@QEAAXXZ@4HA
_BSS	SEGMENT
?flags@?1??DrawEraserMenu@Eraser@@QEAAXXZ@4HA DD 01H DUP (?) ; `Eraser::DrawEraserMenu'::`2'::flags
_BSS	ENDS
;	COMDAT ??_C@_04EBKMHHBE@Size@
CONST	SEGMENT
??_C@_04EBKMHHBE@Size@ DB 'Size', 00H			; `string'
CONST	ENDS
;	COMDAT ??_C@_02NJPGOMH@?$CFf@
CONST	SEGMENT
??_C@_02NJPGOMH@?$CFf@ DB '%f', 00H			; `string'
CONST	ENDS
;	COMDAT ??_C@_0M@HMCLOBBL@Eraser?5tool@
CONST	SEGMENT
??_C@_0M@HMCLOBBL@Eraser?5tool@ DB 'Eraser tool', 00H	; `string'
PUBLIC	?DrawEraserMenu@Eraser@@QEAAXXZ			; Eraser::DrawEraserMenu
PUBLIC	?GetEraserSize@Eraser@@QEAAMXZ			; Eraser::GetEraserSize
PUBLIC	??1Eraser@@QEAA@XZ				; Eraser::~Eraser
PUBLIC	??0Eraser@@QEAA@XZ				; Eraser::Eraser
;	COMDAT pdata
pdata	SEGMENT
$pdata$?DrawEraserMenu@Eraser@@QEAAXXZ DD imagerel $LN12@DrawEraser
	DD	imagerel $LN12@DrawEraser+231
	DD	imagerel $unwind$?DrawEraserMenu@Eraser@@QEAAXXZ
;	COMDAT xdata
xdata	SEGMENT
$unwind$?DrawEraserMenu@Eraser@@QEAAXXZ DQ 03002b20600021519r ; 2.01821e-77
	DD	imagerel __GSHandlerCheck
	DD	050H
END
