; Listing generated by Microsoft (R) Optimizing Compiler Version 19.36.32535.0 

include listing.inc

INCLUDELIB OLDNAMES

PUBLIC	??_C@_0DD@GGDOFOIM@ERROR?3?3FRAMEBUFFER?3?3?5Framebuffe@ ; `string'
;	COMDAT ??_C@_0DD@GGDOFOIM@ERROR?3?3FRAMEBUFFER?3?3?5Framebuffe@
CONST	SEGMENT
??_C@_0DD@GGDOFOIM@ERROR?3?3FRAMEBUFFER?3?3?5Framebuffe@ DB 'ERROR::FRAME'
	DB	'BUFFER:: Framebuffer is not complete!', 0aH, 00H ; `string'
PUBLIC	?GetTexture@Framebuffer@@QEAAIXZ		; Framebuffer::GetTexture
PUBLIC	?Unbind@Framebuffer@@QEAAXXZ			; Framebuffer::Unbind
PUBLIC	?Bind@Framebuffer@@QEAAXXZ			; Framebuffer::Bind
PUBLIC	?Rescale@Framebuffer@@QEAAXPEAE_K1@Z		; Framebuffer::Rescale
PUBLIC	??1Framebuffer@@QEAA@XZ				; Framebuffer::~Framebuffer
PUBLIC	??0Framebuffer@@QEAA@PEAE_K1@Z			; Framebuffer::Framebuffer
;	COMDAT pdata
pdata	SEGMENT
$pdata$?Rescale@Framebuffer@@QEAAXPEAE_K1@Z DD imagerel $LN8@Rescale
	DD	imagerel $LN8@Rescale+186
	DD	imagerel $unwind$?Rescale@Framebuffer@@QEAAXPEAE_K1@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$??1Framebuffer@@QEAA@XZ DD imagerel $LN8@Framebuffe
	DD	imagerel $LN8@Framebuffe+62
	DD	imagerel $unwind$??1Framebuffer@@QEAA@XZ
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$??0Framebuffer@@QEAA@PEAE_K1@Z DD imagerel $LN15@Framebuffe
	DD	imagerel $LN15@Framebuffe+329
	DD	imagerel $unwind$??0Framebuffer@@QEAA@PEAE_K1@Z
;	COMDAT xdata
xdata	SEGMENT
$ip2state$??0Framebuffer@@QEAA@PEAE_K1@Z DD 0f1026e04H
	DW	03H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$stateUnwindMap$??0Framebuffer@@QEAA@PEAE_K1@Z DW 0e02H
	DD	imagerel ?dtor$0@?0???0Framebuffer@@QEAA@PEAE_K1@Z@4HA
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$cppxdata$??0Framebuffer@@QEAA@PEAE_K1@Z DB 028H
	DD	imagerel $stateUnwindMap$??0Framebuffer@@QEAA@PEAE_K1@Z
	DD	imagerel $ip2state$??0Framebuffer@@QEAA@PEAE_K1@Z
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$??0Framebuffer@@QEAA@PEAE_K1@Z DQ 0000c541700081711r ; 1.71449e-308
	DQ	0e0135217000b3417r		; -6.47619e+154
	DD	060107011H
	DD	imagerel __CxxFrameHandler4
	DD	imagerel $cppxdata$??0Framebuffer@@QEAA@PEAE_K1@Z
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$ip2state$??1Framebuffer@@QEAA@XZ DD 02c002406H
	DW	02002H
	DB	00H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$stateUnwindMap$??1Framebuffer@@QEAA@XZ DW 0e02H
	DD	imagerel __std_terminate
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$cppxdata$??1Framebuffer@@QEAA@XZ DB 068H
	DD	imagerel $stateUnwindMap$??1Framebuffer@@QEAA@XZ
	DD	imagerel $ip2state$??1Framebuffer@@QEAA@XZ
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$??1Framebuffer@@QEAA@XZ DQ 03002320600020619r ; 1.96423e-77
	DD	imagerel __CxxFrameHandler4
	DD	imagerel $cppxdata$??1Framebuffer@@QEAA@XZ
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$?Rescale@Framebuffer@@QEAAXPEAE_K1@Z DQ 0000a641400081401r ; 1.44504e-308
	DQ	00008341400095414r		; 1.14083e-308
	DD	070105214H
END
