; Listing generated by Microsoft (R) Optimizing Compiler Version 19.36.32535.0 

include listing.inc

INCLUDELIB OLDNAMES

PUBLIC	??_C@_0DD@GGDOFOIM@ERROR?3?3FRAMEBUFFER?3?3?5Framebuffe@ ; `string'
;	COMDAT ??_C@_0DD@GGDOFOIM@ERROR?3?3FRAMEBUFFER?3?3?5Framebuffe@
CONST	SEGMENT
??_C@_0DD@GGDOFOIM@ERROR?3?3FRAMEBUFFER?3?3?5Framebuffe@ DB 'ERROR::FRAME'
	DB	'BUFFER:: Framebuffer is not complete!', 0aH, 00H ; `string'
PUBLIC	?GetTexture@Framebuffer@@QEAAIXZ		; Framebuffer::GetTexture
PUBLIC	?Unbind@Framebuffer@@QEAAXXZ			; Framebuffer::Unbind
PUBLIC	?Bind@Framebuffer@@QEAAXXZ			; Framebuffer::Bind
PUBLIC	?Rescale@Framebuffer@@QEAAXPEAE_K1@Z		; Framebuffer::Rescale
PUBLIC	??1Framebuffer@@QEAA@XZ				; Framebuffer::~Framebuffer
PUBLIC	??0Framebuffer@@QEAA@PEAE_K1@Z			; Framebuffer::Framebuffer
;	COMDAT pdata
pdata	SEGMENT
$pdata$?Rescale@Framebuffer@@QEAAXPEAE_K1@Z DD imagerel $LN8@Rescale
	DD	imagerel $LN8@Rescale+186
	DD	imagerel $unwind$?Rescale@Framebuffer@@QEAAXPEAE_K1@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$??0Framebuffer@@QEAA@PEAE_K1@Z DD imagerel $LN15@Framebuffe
	DD	imagerel $LN15@Framebuffe+328
	DD	imagerel $unwind$??0Framebuffer@@QEAA@PEAE_K1@Z
;	COMDAT xdata
xdata	SEGMENT
$unwind$??0Framebuffer@@QEAA@PEAE_K1@Z DQ 0000a741500081501r ; 1.45373e-308
	DQ	00008341500096415r		; 1.14083e-308
	DD	0e0115215H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$?Rescale@Framebuffer@@QEAAXPEAE_K1@Z DQ 0000a641400081401r ; 1.44504e-308
	DQ	00008341400095414r		; 1.14083e-308
	DD	070105214H
END
