; Listing generated by Microsoft (R) Optimizing Compiler Version 19.36.32534.0 

include listing.inc

INCLUDELIB OLDNAMES

PUBLIC	??_C@_07EKMDLNDL@windows@			; `string'
PUBLIC	??_C@_05MNMBENCC@cocoa@				; `string'
PUBLIC	??_C@_03JDMECAIF@x11@				; `string'
PUBLIC	??_C@_04JHINAIJO@DIVE@				; `string'
PUBLIC	??_C@_04PIFCDHBF@VMAN@				; `string'
PUBLIC	??_C@_0BA@GCPDENAN@imgui_impl_sdl2@		; `string'
PUBLIC	??_C@_0BN@MCLHEGDM@SDL_MOUSE_FOCUS_CLICKTHROUGH@ ; `string'
PUBLIC	??_C@_01GBGANLPD@0@				; `string'
PUBLIC	??_C@_0BH@LGNEPFCN@SDL_MOUSE_AUTO_CAPTURE@	; `string'
PUBLIC	??_C@_0N@GFDLLEAC@No?5Title?5Yet@		; `string'
EXTRN	__imp_GetWindowLongW:PROC
EXTRN	__imp_SDL_GameControllerGetAxis:PROC
EXTRN	__imp_SDL_WarpMouseGlobal:PROC
EXTRN	__imp_SDL_GetKeyboardFocus:PROC
EXTRN	__imp_SDL_GetPerformanceFrequency:PROC
EXTRN	__imp_SDL_CreateSystemCursor:PROC
EXTRN	__imp_SDL_SetTextInputRect:PROC
EXTRN	__imp_SDL_GameControllerGetButton:PROC
EXTRN	__imp_SDL_SetWindowTitle:PROC
EXTRN	__imp_SDL_FreeCursor:PROC
EXTRN	__imp_SDL_GetDisplayDPI:PROC
EXTRN	__imp_SDL_SetCursor:PROC
EXTRN	__imp_SDL_GetWindowFlags:PROC
EXTRN	__imp_ShowWindow:PROC
EXTRN	__imp_SDL_Vulkan_CreateSurface:PROC
EXTRN	__imp_SDL_ShowWindow:PROC
EXTRN	__imp_SDL_WarpMouseInWindow:PROC
EXTRN	__imp_SDL_SetWindowOpacity:PROC
EXTRN	__imp_SDL_CaptureMouse:PROC
EXTRN	__imp_SDL_GetClipboardText:PROC
EXTRN	__imp_SDL_GetCurrentVideoDriver:PROC
EXTRN	__imp_SDL_SetWindowPosition:PROC
EXTRN	__imp_SDL_SetClipboardText:PROC
EXTRN	__imp_SDL_IsGameController:PROC
EXTRN	__imp_SDL_GameControllerOpen:PROC
EXTRN	__imp_SDL_ShowCursor:PROC
EXTRN	__imp_SDL_GameControllerClose:PROC
EXTRN	__imp_SDL_GetNumVideoDisplays:PROC
EXTRN	__imp_SDL_NumJoysticks:PROC
EXTRN	__imp_SetWindowLongW:PROC
EXTRN	__imp_SDL_GetDisplayBounds:PROC
EXTRN	__imp_SDL_GL_GetDrawableSize:PROC
EXTRN	__imp_SDL_GetWindowFromID:PROC
EXTRN	__imp_SDL_GetDisplayUsableBounds:PROC
EXTRN	__imp_SDL_GetRendererOutputSize:PROC
EXTRN	__imp_SDL_free:PROC
EXTRN	__imp_SDL_SetWindowSize:PROC
EXTRN	__imp_SDL_RaiseWindow:PROC
EXTRN	__imp_SDL_GetPerformanceCounter:PROC
;	COMDAT ??_C@_0N@GFDLLEAC@No?5Title?5Yet@
CONST	SEGMENT
??_C@_0N@GFDLLEAC@No?5Title?5Yet@ DB 'No Title Yet', 00H ; `string'
CONST	ENDS
;	COMDAT ??_C@_0BH@LGNEPFCN@SDL_MOUSE_AUTO_CAPTURE@
CONST	SEGMENT
??_C@_0BH@LGNEPFCN@SDL_MOUSE_AUTO_CAPTURE@ DB 'SDL_MOUSE_AUTO_CAPTURE', 00H ; `string'
CONST	ENDS
;	COMDAT ??_C@_01GBGANLPD@0@
CONST	SEGMENT
??_C@_01GBGANLPD@0@ DB '0', 00H				; `string'
CONST	ENDS
;	COMDAT ??_C@_0BN@MCLHEGDM@SDL_MOUSE_FOCUS_CLICKTHROUGH@
CONST	SEGMENT
??_C@_0BN@MCLHEGDM@SDL_MOUSE_FOCUS_CLICKTHROUGH@ DB 'SDL_MOUSE_FOCUS_CLIC'
	DB	'KTHROUGH', 00H				; `string'
CONST	ENDS
;	COMDAT ??_C@_0BA@GCPDENAN@imgui_impl_sdl2@
CONST	SEGMENT
??_C@_0BA@GCPDENAN@imgui_impl_sdl2@ DB 'imgui_impl_sdl2', 00H ; `string'
CONST	ENDS
;	COMDAT ??_C@_04PIFCDHBF@VMAN@
CONST	SEGMENT
??_C@_04PIFCDHBF@VMAN@ DB 'VMAN', 00H			; `string'
CONST	ENDS
;	COMDAT ??_C@_04JHINAIJO@DIVE@
CONST	SEGMENT
??_C@_04JHINAIJO@DIVE@ DB 'DIVE', 00H			; `string'
CONST	ENDS
;	COMDAT ??_C@_03JDMECAIF@x11@
CONST	SEGMENT
??_C@_03JDMECAIF@x11@ DB 'x11', 00H			; `string'
CONST	ENDS
;	COMDAT ??_C@_05MNMBENCC@cocoa@
CONST	SEGMENT
??_C@_05MNMBENCC@cocoa@ DB 'cocoa', 00H			; `string'
CONST	ENDS
;	COMDAT ??_C@_07EKMDLNDL@windows@
CONST	SEGMENT
??_C@_07EKMDLNDL@windows@ DB 'windows', 00H		; `string'
