; Listing generated by Microsoft (R) Optimizing Compiler Version 19.36.32534.0 

include listing.inc

INCLUDELIB OLDNAMES

PUBLIC	??_C@_0BD@BJOEHOL@imgui_impl_opengl2@		; `string'
EXTRN	__imp_glGetIntegerv:PROC
EXTRN	__imp_glPushAttrib:PROC
EXTRN	__imp_glOrtho:PROC
EXTRN	__imp_glPixelStorei:PROC
EXTRN	__imp_glShadeModel:PROC
EXTRN	__imp_glPushMatrix:PROC
EXTRN	__imp_glDisable:PROC
EXTRN	__imp_glDrawElements:PROC
EXTRN	__imp_glTexEnvi:PROC
EXTRN	__imp_glColorPointer:PROC
EXTRN	__imp_glTexImage2D:PROC
EXTRN	__imp_glClearColor:PROC
EXTRN	__imp_glGetTexEnviv:PROC
EXTRN	__imp_glTexCoordPointer:PROC
EXTRN	__imp_glDeleteTextures:PROC
EXTRN	__imp_glTexParameteri:PROC
EXTRN	__imp_glLoadIdentity:PROC
EXTRN	__imp_glBlendFunc:PROC
EXTRN	__imp_glMatrixMode:PROC
EXTRN	__imp_glDisableClientState:PROC
EXTRN	__imp_glScissor:PROC
EXTRN	__imp_glEnable:PROC
EXTRN	__imp_glVertexPointer:PROC
EXTRN	__imp_glGenTextures:PROC
EXTRN	__imp_glBindTexture:PROC
EXTRN	__imp_glPolygonMode:PROC
EXTRN	__imp_glPopAttrib:PROC
EXTRN	__imp_glClear:PROC
EXTRN	__imp_glEnableClientState:PROC
EXTRN	__imp_glViewport:PROC
EXTRN	__imp_glPopMatrix:PROC
