; Listing generated by Microsoft (R) Optimizing Compiler Version 19.36.32535.0 

include listing.inc

INCLUDELIB OLDNAMES

PUBLIC	??_C@_0M@LODKKDJJ@?$CD?$CDInstances@		; `string'
PUBLIC	??_C@_01DNKMNLPK@?$HM@				; `string'
PUBLIC	??_C@_0BA@HPJOFHBN@?$CD?$CDAngledHeaders@	; `string'
PUBLIC	??_C@_0O@BMOANCPA@?$CD?$CDContextMenu@		; `string'
PUBLIC	??_C@_09MGFHLAFE@?$DMUnknown?$DO@		; `string'
PUBLIC	??_C@_09BDLBIGPI@0x?$CF08X?0?$CFd@		; `string'
PUBLIC	??_C@_0M@LAOOHBLO@RefScale?$DN?$CFf@		; `string'
PUBLIC	??_C@_0M@JOECNJOM@Column?5?$CFd?$CFn@		; `string'
PUBLIC	??_C@_0BA@KAIOJKEL@UserID?$DN0x?$CF08X?$CFn@	; `string'
PUBLIC	??_C@_0L@LJLKPCDP@Width?$DN?$CFd?$CFn@		; `string'
PUBLIC	??_C@_0M@IJODOCHC@Weight?$DN?$CFf?$CFn@		; `string'
PUBLIC	??_C@_0N@EKALHFOF@Visible?$DN?$CFd?$CFn@	; `string'
PUBLIC	??_C@_0L@BHOFPJL@Order?$DN?$CFd?$CFn@		; `string'
PUBLIC	??_C@_0M@KGHCDDIO@Sort?$DN?$CFd?$CFc?$CFn@	; `string'
PUBLIC	??_C@_0BB@PGHPBJD@?$FL?$CFs?$FN?$FL0x?$CF08X?0?$CFd?$FN?6@ ; `string'
PUBLIC	??_C@_0N@NHEEPCEH@RefScale?$DN?$CFg?6@		; `string'
PUBLIC	??_C@_0M@JLNIJDCE@Column?5?$CF?92d@		; `string'
PUBLIC	??_C@_0N@PGBEGIHP@?5UserID?$DN?$CF08X@		; `string'
PUBLIC	??_C@_0N@MFKBBKPH@?5Weight?$DN?$CF?44f@		; `string'
PUBLIC	??_C@_09PBOBBCAP@?5Width?$DN?$CFd@		; `string'
PUBLIC	??_C@_0M@CIPDPODB@?5Visible?$DN?$CFd@		; `string'
PUBLIC	??_C@_09CFPCIBAG@?5Order?$DN?$CFd@		; `string'
PUBLIC	??_C@_0L@EAJILIBD@?5Sort?$DN?$CFd?$CFc@		; `string'
PUBLIC	??_C@_08CCPMLANI@FixedFit@			; `string'
PUBLIC	??_C@_09OOODJBFG@FixedSame@			; `string'
PUBLIC	??_C@_0M@IGAOBHEB@StretchProp@			; `string'
PUBLIC	??_C@_0M@LHDDKHJK@StretchSame@			; `string'
PUBLIC	??_C@_0CF@DAHKPIHJ@Table?50x?$CF08X?5?$CI?$CFd?5columns?0?5in?5?8?$CF@ ; `string'
PUBLIC	??_C@_0EM@JLKLPOOK@?$CK?$CK?5?$CFd?5instances?5of?5same?5table?$CB?5@ ; `string'
PUBLIC	??_C@_0BA@KDHINKIA@in?5BeginTable?$CI?$CJ@	; `string'
PUBLIC	??_C@_0P@MDFKNKGM@Clear?5settings@		; `string'
PUBLIC	??_C@_0DL@BMMMGOOI@OuterRect?3?5Pos?3?5?$CI?$CF?41f?0?$CF?41f?$CJ?5Siz@ ; `string'
PUBLIC	??_C@_07IOPDKCEG@?5?$CIauto?$CJ@		; `string'
PUBLIC	??_C@_0EH@GODPECNO@ColumnsGivenWidth?3?5?$CF?41f?0?5Column@ ; `string'
PUBLIC	??_C@_0EB@FOKPBOFF@CellPaddingX?3?5?$CF?41f?0?5CellSpacing@ ; `string'
PUBLIC	??_C@_0CP@NOMNLPPG@HoveredColumnBody?3?5?$CFd?0?5HoveredC@ ; `string'
PUBLIC	??_C@_0DL@PBPICJCB@ResizedColumn?3?5?$CFd?0?5ReorderColum@ ; `string'
PUBLIC	??_C@_0DD@FILHJAIB@Instance?5?$CFd?3?5HoveredRow?3?5?$CFd?0?5La@ ; `string'
PUBLIC	??_C@_09BHNPHONE@NoResize?5@			; `string'
PUBLIC	??_C@_0M@IGDNFKMD@WidthFixed?5@			; `string'
PUBLIC	??_C@_0O@PEPBBILL@WidthStretch?5@		; `string'
PUBLIC	??_C@_06FEBPAKFP@?5?$CIAsc?$CJ@			; `string'
PUBLIC	??_C@_06PFKLCOBM@?5?$CIDes?$CJ@			; `string'
PUBLIC	??_C@_09LODDIFJL@?5?$CIFrozen?$CJ@		; `string'
PUBLIC	??_C@_0BHH@CNHMONCM@Column?5?$CFd?5order?5?$CFd?5?8?$CFs?8?3?5offset@ ; `string'
PUBLIC	??_C@_0BN@LNKMILO@Settings?50x?$CF08X?5?$CI?$CFd?5columns?$CJ@ ; `string'
PUBLIC	??_C@_0BC@LJHOAHJA@SaveFlags?3?50x?$CF08X@	; `string'
PUBLIC	??_C@_0BK@OLKPLDMA@ColumnsCount?3?5?$CFd?5?$CImax?5?$CFd?$CJ@ ; `string'
PUBLIC	??_C@_06ODJMJFLN@Weight@			; `string'
PUBLIC	??_C@_06PALFPBFG@Width?5@			; `string'
PUBLIC	??_C@_03OFHEPBNG@Asc@				; `string'
PUBLIC	??_C@_03IAMDMMHH@Des@				; `string'
PUBLIC	??_C@_03JMFMNIFM@?9?9?9@			; `string'
PUBLIC	??_C@_0EB@CNABLLAJ@Column?5?$CFd?5Order?5?$CFd?5SortOrder?5?$CFd@ ; `string'
PUBLIC	??_C@_07HIFEPIJN@columns@			; `string'
;	COMDAT ??_C@_07HIFEPIJN@columns@
CONST	SEGMENT
??_C@_07HIFEPIJN@columns@ DB 'columns', 00H		; `string'
CONST	ENDS
;	COMDAT ??_C@_0EB@CNABLLAJ@Column?5?$CFd?5Order?5?$CFd?5SortOrder?5?$CFd@
CONST	SEGMENT
??_C@_0EB@CNABLLAJ@Column?5?$CFd?5Order?5?$CFd?5SortOrder?5?$CFd@ DB 'Col'
	DB	'umn %d Order %d SortOrder %d %s Vis %d %s %7.3f UserID 0x%08X'
	DB	00H						; `string'
CONST	ENDS
;	COMDAT ??_C@_03JMFMNIFM@?9?9?9@
CONST	SEGMENT
??_C@_03JMFMNIFM@?9?9?9@ DB '---', 00H			; `string'
CONST	ENDS
;	COMDAT ??_C@_03IAMDMMHH@Des@
CONST	SEGMENT
??_C@_03IAMDMMHH@Des@ DB 'Des', 00H			; `string'
CONST	ENDS
;	COMDAT ??_C@_03OFHEPBNG@Asc@
CONST	SEGMENT
??_C@_03OFHEPBNG@Asc@ DB 'Asc', 00H			; `string'
CONST	ENDS
;	COMDAT ??_C@_06PALFPBFG@Width?5@
CONST	SEGMENT
??_C@_06PALFPBFG@Width?5@ DB 'Width ', 00H		; `string'
CONST	ENDS
;	COMDAT ??_C@_06ODJMJFLN@Weight@
CONST	SEGMENT
??_C@_06ODJMJFLN@Weight@ DB 'Weight', 00H		; `string'
CONST	ENDS
;	COMDAT ??_C@_0BK@OLKPLDMA@ColumnsCount?3?5?$CFd?5?$CImax?5?$CFd?$CJ@
CONST	SEGMENT
??_C@_0BK@OLKPLDMA@ColumnsCount?3?5?$CFd?5?$CImax?5?$CFd?$CJ@ DB 'Columns'
	DB	'Count: %d (max %d)', 00H			; `string'
CONST	ENDS
;	COMDAT ??_C@_0BC@LJHOAHJA@SaveFlags?3?50x?$CF08X@
CONST	SEGMENT
??_C@_0BC@LJHOAHJA@SaveFlags?3?50x?$CF08X@ DB 'SaveFlags: 0x%08X', 00H ; `string'
CONST	ENDS
;	COMDAT ??_C@_0BN@LNKMILO@Settings?50x?$CF08X?5?$CI?$CFd?5columns?$CJ@
CONST	SEGMENT
??_C@_0BN@LNKMILO@Settings?50x?$CF08X?5?$CI?$CFd?5columns?$CJ@ DB 'Settin'
	DB	'gs 0x%08X (%d columns)', 00H		; `string'
CONST	ENDS
;	COMDAT ??_C@_0BHH@CNHMONCM@Column?5?$CFd?5order?5?$CFd?5?8?$CFs?8?3?5offset@
CONST	SEGMENT
??_C@_0BHH@CNHMONCM@Column?5?$CFd?5order?5?$CFd?5?8?$CFs?8?3?5offset@ DB 'C'
	DB	'olumn %d order %d ''%s'': offset %+.2f to %+.2f%s', 0aH, 'Ena'
	DB	'bled: %d, VisibleX/Y: %d/%d, RequestOutput: %d, SkipItems: %d'
	DB	', DrawChannels: %d,%d', 0aH, 'WidthGiven: %.1f, Request/Auto:'
	DB	' %.1f/%.1f, StretchWeight: %.3f (%.1f%%)', 0aH, 'MinX: %.1f, '
	DB	'MaxX: %.1f (%+.1f), ClipRect: %.1f to %.1f (+%.1f)', 0aH, 'Co'
	DB	'ntentWidth: %.1f,%.1f, HeadersUsed/Ideal %.1f/%.1f', 0aH, 'So'
	DB	'rt: %d%s, UserID: 0x%08X, Flags: 0x%04X: %s%s%s..', 00H ; `string'
CONST	ENDS
;	COMDAT ??_C@_09LODDIFJL@?5?$CIFrozen?$CJ@
CONST	SEGMENT
??_C@_09LODDIFJL@?5?$CIFrozen?$CJ@ DB ' (Frozen)', 00H	; `string'
CONST	ENDS
;	COMDAT ??_C@_06PFKLCOBM@?5?$CIDes?$CJ@
CONST	SEGMENT
??_C@_06PFKLCOBM@?5?$CIDes?$CJ@ DB ' (Des)', 00H	; `string'
CONST	ENDS
;	COMDAT ??_C@_06FEBPAKFP@?5?$CIAsc?$CJ@
CONST	SEGMENT
??_C@_06FEBPAKFP@?5?$CIAsc?$CJ@ DB ' (Asc)', 00H	; `string'
CONST	ENDS
;	COMDAT ??_C@_0O@PEPBBILL@WidthStretch?5@
CONST	SEGMENT
??_C@_0O@PEPBBILL@WidthStretch?5@ DB 'WidthStretch ', 00H ; `string'
CONST	ENDS
;	COMDAT ??_C@_0M@IGDNFKMD@WidthFixed?5@
CONST	SEGMENT
??_C@_0M@IGDNFKMD@WidthFixed?5@ DB 'WidthFixed ', 00H	; `string'
CONST	ENDS
;	COMDAT ??_C@_09BHNPHONE@NoResize?5@
CONST	SEGMENT
??_C@_09BHNPHONE@NoResize?5@ DB 'NoResize ', 00H	; `string'
CONST	ENDS
;	COMDAT ??_C@_0DD@FILHJAIB@Instance?5?$CFd?3?5HoveredRow?3?5?$CFd?0?5La@
CONST	SEGMENT
??_C@_0DD@FILHJAIB@Instance?5?$CFd?3?5HoveredRow?3?5?$CFd?0?5La@ DB 'Inst'
	DB	'ance %d: HoveredRow: %d, LastOuterHeight: %.2f', 00H ; `string'
CONST	ENDS
;	COMDAT ??_C@_0DL@PBPICJCB@ResizedColumn?3?5?$CFd?0?5ReorderColum@
CONST	SEGMENT
??_C@_0DL@PBPICJCB@ResizedColumn?3?5?$CFd?0?5ReorderColum@ DB 'ResizedCol'
	DB	'umn: %d, ReorderColumn: %d, HeldHeaderColumn: %d', 00H ; `string'
CONST	ENDS
;	COMDAT ??_C@_0CP@NOMNLPPG@HoveredColumnBody?3?5?$CFd?0?5HoveredC@
CONST	SEGMENT
??_C@_0CP@NOMNLPPG@HoveredColumnBody?3?5?$CFd?0?5HoveredC@ DB 'HoveredCol'
	DB	'umnBody: %d, HoveredColumnBorder: %d', 00H	; `string'
CONST	ENDS
;	COMDAT ??_C@_0EB@FOKPBOFF@CellPaddingX?3?5?$CF?41f?0?5CellSpacing@
CONST	SEGMENT
??_C@_0EB@FOKPBOFF@CellPaddingX?3?5?$CF?41f?0?5CellSpacing@ DB 'CellPaddi'
	DB	'ngX: %.1f, CellSpacingX: %.1f/%.1f, OuterPaddingX: %.1f', 00H ; `string'
CONST	ENDS
;	COMDAT ??_C@_0EH@GODPECNO@ColumnsGivenWidth?3?5?$CF?41f?0?5Column@
CONST	SEGMENT
??_C@_0EH@GODPECNO@ColumnsGivenWidth?3?5?$CF?41f?0?5Column@ DB 'ColumnsGi'
	DB	'venWidth: %.1f, ColumnsAutoFitWidth: %.1f, InnerWidth: %.1f%s'
	DB	00H						; `string'
CONST	ENDS
;	COMDAT ??_C@_07IOPDKCEG@?5?$CIauto?$CJ@
CONST	SEGMENT
??_C@_07IOPDKCEG@?5?$CIauto?$CJ@ DB ' (auto)', 00H	; `string'
CONST	ENDS
;	COMDAT ??_C@_0DL@BMMMGOOI@OuterRect?3?5Pos?3?5?$CI?$CF?41f?0?$CF?41f?$CJ?5Siz@
CONST	SEGMENT
??_C@_0DL@BMMMGOOI@OuterRect?3?5Pos?3?5?$CI?$CF?41f?0?$CF?41f?$CJ?5Siz@ DB 'O'
	DB	'uterRect: Pos: (%.1f,%.1f) Size: (%.1f,%.1f) Sizing: ''%s''', 00H ; `string'
CONST	ENDS
;	COMDAT ??_C@_0P@MDFKNKGM@Clear?5settings@
CONST	SEGMENT
??_C@_0P@MDFKNKGM@Clear?5settings@ DB 'Clear settings', 00H ; `string'
CONST	ENDS
;	COMDAT ??_C@_0BA@KDHINKIA@in?5BeginTable?$CI?$CJ@
CONST	SEGMENT
??_C@_0BA@KDHINKIA@in?5BeginTable?$CI?$CJ@ DB 'in BeginTable()', 00H ; `string'
CONST	ENDS
;	COMDAT ??_C@_0EM@JLKLPOOK@?$CK?$CK?5?$CFd?5instances?5of?5same?5table?$CB?5@
CONST	SEGMENT
??_C@_0EM@JLKLPOOK@?$CK?$CK?5?$CFd?5instances?5of?5same?5table?$CB?5@ DB '*'
	DB	'* %d instances of same table! Some data below will refer to l'
	DB	'ast instance.', 00H				; `string'
CONST	ENDS
;	COMDAT ??_C@_0CF@DAHKPIHJ@Table?50x?$CF08X?5?$CI?$CFd?5columns?0?5in?5?8?$CF@
CONST	SEGMENT
??_C@_0CF@DAHKPIHJ@Table?50x?$CF08X?5?$CI?$CFd?5columns?0?5in?5?8?$CF@ DB 'T'
	DB	'able 0x%08X (%d columns, in ''%s'')%s', 00H	; `string'
CONST	ENDS
;	COMDAT ??_C@_0M@LHDDKHJK@StretchSame@
CONST	SEGMENT
??_C@_0M@LHDDKHJK@StretchSame@ DB 'StretchSame', 00H	; `string'
CONST	ENDS
;	COMDAT ??_C@_0M@IGAOBHEB@StretchProp@
CONST	SEGMENT
??_C@_0M@IGAOBHEB@StretchProp@ DB 'StretchProp', 00H	; `string'
CONST	ENDS
;	COMDAT ??_C@_09OOODJBFG@FixedSame@
CONST	SEGMENT
??_C@_09OOODJBFG@FixedSame@ DB 'FixedSame', 00H		; `string'
CONST	ENDS
;	COMDAT ??_C@_08CCPMLANI@FixedFit@
CONST	SEGMENT
??_C@_08CCPMLANI@FixedFit@ DB 'FixedFit', 00H		; `string'
CONST	ENDS
;	COMDAT ??_C@_0L@EAJILIBD@?5Sort?$DN?$CFd?$CFc@
CONST	SEGMENT
??_C@_0L@EAJILIBD@?5Sort?$DN?$CFd?$CFc@ DB ' Sort=%d%c', 00H ; `string'
CONST	ENDS
;	COMDAT ??_C@_09CFPCIBAG@?5Order?$DN?$CFd@
CONST	SEGMENT
??_C@_09CFPCIBAG@?5Order?$DN?$CFd@ DB ' Order=%d', 00H	; `string'
CONST	ENDS
;	COMDAT ??_C@_0M@CIPDPODB@?5Visible?$DN?$CFd@
CONST	SEGMENT
??_C@_0M@CIPDPODB@?5Visible?$DN?$CFd@ DB ' Visible=%d', 00H ; `string'
CONST	ENDS
;	COMDAT ??_C@_09PBOBBCAP@?5Width?$DN?$CFd@
CONST	SEGMENT
??_C@_09PBOBBCAP@?5Width?$DN?$CFd@ DB ' Width=%d', 00H	; `string'
CONST	ENDS
;	COMDAT ??_C@_0N@MFKBBKPH@?5Weight?$DN?$CF?44f@
CONST	SEGMENT
??_C@_0N@MFKBBKPH@?5Weight?$DN?$CF?44f@ DB ' Weight=%.4f', 00H ; `string'
CONST	ENDS
;	COMDAT ??_C@_0N@PGBEGIHP@?5UserID?$DN?$CF08X@
CONST	SEGMENT
??_C@_0N@PGBEGIHP@?5UserID?$DN?$CF08X@ DB ' UserID=%08X', 00H ; `string'
CONST	ENDS
;	COMDAT ??_C@_0M@JLNIJDCE@Column?5?$CF?92d@
CONST	SEGMENT
??_C@_0M@JLNIJDCE@Column?5?$CF?92d@ DB 'Column %-2d', 00H ; `string'
CONST	ENDS
;	COMDAT ??_C@_0N@NHEEPCEH@RefScale?$DN?$CFg?6@
CONST	SEGMENT
??_C@_0N@NHEEPCEH@RefScale?$DN?$CFg?6@ DB 'RefScale=%g', 0aH, 00H ; `string'
CONST	ENDS
;	COMDAT ??_C@_0BB@PGHPBJD@?$FL?$CFs?$FN?$FL0x?$CF08X?0?$CFd?$FN?6@
CONST	SEGMENT
??_C@_0BB@PGHPBJD@?$FL?$CFs?$FN?$FL0x?$CF08X?0?$CFd?$FN?6@ DB '[%s][0x%08'
	DB	'X,%d]', 0aH, 00H				; `string'
CONST	ENDS
;	COMDAT ??_C@_0M@KGHCDDIO@Sort?$DN?$CFd?$CFc?$CFn@
CONST	SEGMENT
??_C@_0M@KGHCDDIO@Sort?$DN?$CFd?$CFc?$CFn@ DB 'Sort=%d%c%n', 00H ; `string'
CONST	ENDS
;	COMDAT ??_C@_0L@BHOFPJL@Order?$DN?$CFd?$CFn@
CONST	SEGMENT
??_C@_0L@BHOFPJL@Order?$DN?$CFd?$CFn@ DB 'Order=%d%n', 00H ; `string'
CONST	ENDS
;	COMDAT ??_C@_0N@EKALHFOF@Visible?$DN?$CFd?$CFn@
CONST	SEGMENT
??_C@_0N@EKALHFOF@Visible?$DN?$CFd?$CFn@ DB 'Visible=%d%n', 00H ; `string'
CONST	ENDS
;	COMDAT ??_C@_0M@IJODOCHC@Weight?$DN?$CFf?$CFn@
CONST	SEGMENT
??_C@_0M@IJODOCHC@Weight?$DN?$CFf?$CFn@ DB 'Weight=%f%n', 00H ; `string'
CONST	ENDS
;	COMDAT ??_C@_0L@LJLKPCDP@Width?$DN?$CFd?$CFn@
CONST	SEGMENT
??_C@_0L@LJLKPCDP@Width?$DN?$CFd?$CFn@ DB 'Width=%d%n', 00H ; `string'
CONST	ENDS
;	COMDAT ??_C@_0BA@KAIOJKEL@UserID?$DN0x?$CF08X?$CFn@
CONST	SEGMENT
??_C@_0BA@KAIOJKEL@UserID?$DN0x?$CF08X?$CFn@ DB 'UserID=0x%08X%n', 00H ; `string'
CONST	ENDS
;	COMDAT ??_C@_0M@JOECNJOM@Column?5?$CFd?$CFn@
CONST	SEGMENT
??_C@_0M@JOECNJOM@Column?5?$CFd?$CFn@ DB 'Column %d%n', 00H ; `string'
CONST	ENDS
;	COMDAT ??_C@_0M@LAOOHBLO@RefScale?$DN?$CFf@
CONST	SEGMENT
??_C@_0M@LAOOHBLO@RefScale?$DN?$CFf@ DB 'RefScale=%f', 00H ; `string'
CONST	ENDS
;	COMDAT ??_C@_09BDLBIGPI@0x?$CF08X?0?$CFd@
CONST	SEGMENT
??_C@_09BDLBIGPI@0x?$CF08X?0?$CFd@ DB '0x%08X,%d', 00H	; `string'
CONST	ENDS
;	COMDAT ??_C@_09MGFHLAFE@?$DMUnknown?$DO@
CONST	SEGMENT
??_C@_09MGFHLAFE@?$DMUnknown?$DO@ DB '<Unknown>', 00H	; `string'
CONST	ENDS
;	COMDAT ??_C@_0O@BMOANCPA@?$CD?$CDContextMenu@
CONST	SEGMENT
??_C@_0O@BMOANCPA@?$CD?$CDContextMenu@ DB '##ContextMenu', 00H ; `string'
CONST	ENDS
;	COMDAT ??_C@_0BA@HPJOFHBN@?$CD?$CDAngledHeaders@
CONST	SEGMENT
??_C@_0BA@HPJOFHBN@?$CD?$CDAngledHeaders@ DB '##AngledHeaders', 00H ; `string'
CONST	ENDS
;	COMDAT ??_C@_01DNKMNLPK@?$HM@
CONST	SEGMENT
??_C@_01DNKMNLPK@?$HM@ DB '|', 00H			; `string'
CONST	ENDS
;	COMDAT ??_C@_0M@LODKKDJJ@?$CD?$CDInstances@
CONST	SEGMENT
??_C@_0M@LODKKDJJ@?$CD?$CDInstances@ DB '##Instances', 00H ; `string'
PUBLIC	?swap@?$ImVector@D@@QEAAXAEAU1@@Z		; ImVector<char>::swap
PUBLIC	??A?$ImVector@UImGuiOldColumnData@@@@QEAAAEAUImGuiOldColumnData@@H@Z ; ImVector<ImGuiOldColumnData>::operator[]
PUBLIC	?GetIndex@?$ImPool@UImGuiTable@@@@QEBAHPEBUImGuiTable@@@Z ; ImPool<ImGuiTable>::GetIndex
PUBLIC	?clear@?$ImChunkStream@UImGuiTableSettings@@@@QEAAXXZ ; ImChunkStream<ImGuiTableSettings>::clear
PUBLIC	?alloc_chunk@?$ImChunkStream@UImGuiTableSettings@@@@QEAAPEAUImGuiTableSettings@@_K@Z ; ImChunkStream<ImGuiTableSettings>::alloc_chunk
PUBLIC	?swap@?$ImChunkStream@UImGuiTableSettings@@@@QEAAXAEAU1@@Z ; ImChunkStream<ImGuiTableSettings>::swap
PUBLIC	??A?$ImSpan@UImGuiTableColumn@@@@QEBAAEBUImGuiTableColumn@@H@Z ; ImSpan<ImGuiTableColumn>::operator[]
PUBLIC	??A?$ImSpan@UImGuiTableCellData@@@@QEAAAEAUImGuiTableCellData@@H@Z ; ImSpan<ImGuiTableCellData>::operator[]
PUBLIC	?clear@?$ImVector@UImGuiTableColumnSortSpecs@@@@QEAAXXZ ; ImVector<ImGuiTableColumnSortSpecs>::clear
PUBLIC	?PopColumnsBackground@ImGui@@YAXXZ		; ImGui::PopColumnsBackground
PUBLIC	?PushColumnsBackground@ImGui@@YAXXZ		; ImGui::PushColumnsBackground
PUBLIC	?SetColumnOffset@ImGui@@YAXHM@Z			; ImGui::SetColumnOffset
PUBLIC	?GetColumnNormFromOffset@ImGui@@YAMPEBUImGuiOldColumns@@M@Z ; ImGui::GetColumnNormFromOffset
PUBLIC	?SetWindowClipRectBeforeSetChannel@ImGui@@YAXPEAUImGuiWindow@@AEBUImRect@@@Z ; ImGui::SetWindowClipRectBeforeSetChannel
PUBLIC	?TableSettingsFindByID@ImGui@@YAPEAUImGuiTableSettings@@I@Z ; ImGui::TableSettingsFindByID
PUBLIC	?TableSettingsCreate@ImGui@@YAPEAUImGuiTableSettings@@IH@Z ; ImGui::TableSettingsCreate
PUBLIC	?TablePopBackgroundChannel@ImGui@@YAXXZ		; ImGui::TablePopBackgroundChannel
PUBLIC	?TablePushBackgroundChannel@ImGui@@YAXXZ	; ImGui::TablePushBackgroundChannel
PUBLIC	?TableEndCell@ImGui@@YAXPEAUImGuiTable@@@Z	; ImGui::TableEndCell
PUBLIC	?TableGetCellBgRect@ImGui@@YA?AUImRect@@PEBUImGuiTable@@H@Z ; ImGui::TableGetCellBgRect
PUBLIC	?ItemSize@ImGui@@YAXAEBUImRect@@M@Z		; ImGui::ItemSize
PUBLIC	?GetColumnSettings@ImGuiTableSettings@@QEAAPEAUImGuiTableColumnSettings@@XZ ; ImGuiTableSettings::GetColumnSettings
PUBLIC	??0ImGuiTableSettings@@QEAA@XZ			; ImGuiTableSettings::ImGuiTableSettings
PUBLIC	??0ImGuiTableColumnSettings@@QEAA@XZ		; ImGuiTableColumnSettings::ImGuiTableColumnSettings
PUBLIC	?GetColumnOffset@ImGui@@YAMH@Z			; ImGui::GetColumnOffset
PUBLIC	?EndColumns@ImGui@@YAXXZ			; ImGui::EndColumns
PUBLIC	?GetColumnOffsetFromNorm@ImGui@@YAMPEBUImGuiOldColumns@@M@Z ; ImGui::GetColumnOffsetFromNorm
PUBLIC	?TableGcCompactSettings@ImGui@@YAXXZ		; ImGui::TableGcCompactSettings
PUBLIC	?TableGcCompactTransientBuffers@ImGui@@YAXPEAUImGuiTable@@@Z ; ImGui::TableGcCompactTransientBuffers
PUBLIC	?TableGcCompactTransientBuffers@ImGui@@YAXPEAUImGuiTableTempData@@@Z ; ImGui::TableGcCompactTransientBuffers
PUBLIC	?TableSettingsAddSettingsHandler@ImGui@@YAXXZ	; ImGui::TableSettingsAddSettingsHandler
PUBLIC	?TableEndRow@ImGui@@YAXPEAUImGuiTable@@@Z	; ImGui::TableEndRow
;	COMDAT pdata
pdata	SEGMENT
$pdata$?alloc_chunk@?$ImChunkStream@UImGuiTableSettings@@@@QEAAPEAUImGuiTableSettings@@_K@Z DD imagerel $LN13@alloc_chun
	DD	imagerel $LN13@alloc_chun+119
	DD	imagerel $unwind$?alloc_chunk@?$ImChunkStream@UImGuiTableSettings@@@@QEAAPEAUImGuiTableSettings@@_K@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$?clear@?$ImVector@UImGuiTableColumnSortSpecs@@@@QEAAXXZ DD imagerel $LN21@clear
	DD	imagerel $LN21@clear+29
	DD	imagerel $unwind$?clear@?$ImVector@UImGuiTableColumnSortSpecs@@@@QEAAXXZ
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$0$?clear@?$ImVector@UImGuiTableColumnSortSpecs@@@@QEAAXXZ DD imagerel $LN21@clear+29
	DD	imagerel $LN21@clear+157
	DD	imagerel $chain$0$?clear@?$ImVector@UImGuiTableColumnSortSpecs@@@@QEAAXXZ
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$1$?clear@?$ImVector@UImGuiTableColumnSortSpecs@@@@QEAAXXZ DD imagerel $LN21@clear+157
	DD	imagerel $LN21@clear+163
	DD	imagerel $chain$1$?clear@?$ImVector@UImGuiTableColumnSortSpecs@@@@QEAAXXZ
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$?PopColumnsBackground@ImGui@@YAXXZ DD imagerel $LN11@PopColumns
	DD	imagerel $LN11@PopColumns+196
	DD	imagerel $unwind$?PopColumnsBackground@ImGui@@YAXXZ
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$?PushColumnsBackground@ImGui@@YAXXZ DD imagerel $LN11@PushColumn
	DD	imagerel $LN11@PushColumn+205
	DD	imagerel $unwind$?PushColumnsBackground@ImGui@@YAXXZ
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$?SetColumnOffset@ImGui@@YAXHM@Z DD imagerel $LN58@SetColumnO
	DD	imagerel $LN58@SetColumnO+301
	DD	imagerel $unwind$?SetColumnOffset@ImGui@@YAXHM@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$?SetWindowClipRectBeforeSetChannel@ImGui@@YAXPEAUImGuiWindow@@AEBUImRect@@@Z DD imagerel $LN8@SetWindowC
	DD	imagerel $LN8@SetWindowC+127
	DD	imagerel $unwind$?SetWindowClipRectBeforeSetChannel@ImGui@@YAXPEAUImGuiWindow@@AEBUImRect@@@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$?TableSettingsHandler_WriteAll@@YAXPEAUImGuiContext@@PEAUImGuiSettingsHandler@@PEAUImGuiTextBuffer@@@Z DD imagerel ?TableSettingsHandler_WriteAll@@YAXPEAUImGuiContext@@PEAUImGuiSettingsHandler@@PEAUImGuiTextBuffer@@@Z
	DD	imagerel ?TableSettingsHandler_WriteAll@@YAXPEAUImGuiContext@@PEAUImGuiSettingsHandler@@PEAUImGuiTextBuffer@@@Z+42
	DD	imagerel $unwind$?TableSettingsHandler_WriteAll@@YAXPEAUImGuiContext@@PEAUImGuiSettingsHandler@@PEAUImGuiTextBuffer@@@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$0$?TableSettingsHandler_WriteAll@@YAXPEAUImGuiContext@@PEAUImGuiSettingsHandler@@PEAUImGuiTextBuffer@@@Z DD imagerel ?TableSettingsHandler_WriteAll@@YAXPEAUImGuiContext@@PEAUImGuiSettingsHandler@@PEAUImGuiTextBuffer@@@Z+42
	DD	imagerel ?TableSettingsHandler_WriteAll@@YAXPEAUImGuiContext@@PEAUImGuiSettingsHandler@@PEAUImGuiTextBuffer@@@Z+59
	DD	imagerel $chain$0$?TableSettingsHandler_WriteAll@@YAXPEAUImGuiContext@@PEAUImGuiSettingsHandler@@PEAUImGuiTextBuffer@@@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$6$?TableSettingsHandler_WriteAll@@YAXPEAUImGuiContext@@PEAUImGuiSettingsHandler@@PEAUImGuiTextBuffer@@@Z DD imagerel ?TableSettingsHandler_WriteAll@@YAXPEAUImGuiContext@@PEAUImGuiSettingsHandler@@PEAUImGuiTextBuffer@@@Z+59
	DD	imagerel ?TableSettingsHandler_WriteAll@@YAXPEAUImGuiContext@@PEAUImGuiSettingsHandler@@PEAUImGuiTextBuffer@@@Z+920
	DD	imagerel $chain$6$?TableSettingsHandler_WriteAll@@YAXPEAUImGuiContext@@PEAUImGuiSettingsHandler@@PEAUImGuiTextBuffer@@@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$7$?TableSettingsHandler_WriteAll@@YAXPEAUImGuiContext@@PEAUImGuiSettingsHandler@@PEAUImGuiTextBuffer@@@Z DD imagerel ?TableSettingsHandler_WriteAll@@YAXPEAUImGuiContext@@PEAUImGuiSettingsHandler@@PEAUImGuiTextBuffer@@@Z+920
	DD	imagerel ?TableSettingsHandler_WriteAll@@YAXPEAUImGuiContext@@PEAUImGuiSettingsHandler@@PEAUImGuiTextBuffer@@@Z+925
	DD	imagerel $chain$7$?TableSettingsHandler_WriteAll@@YAXPEAUImGuiContext@@PEAUImGuiSettingsHandler@@PEAUImGuiTextBuffer@@@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$8$?TableSettingsHandler_WriteAll@@YAXPEAUImGuiContext@@PEAUImGuiSettingsHandler@@PEAUImGuiTextBuffer@@@Z DD imagerel ?TableSettingsHandler_WriteAll@@YAXPEAUImGuiContext@@PEAUImGuiSettingsHandler@@PEAUImGuiTextBuffer@@@Z+925
	DD	imagerel ?TableSettingsHandler_WriteAll@@YAXPEAUImGuiContext@@PEAUImGuiSettingsHandler@@PEAUImGuiTextBuffer@@@Z+932
	DD	imagerel $chain$8$?TableSettingsHandler_WriteAll@@YAXPEAUImGuiContext@@PEAUImGuiSettingsHandler@@PEAUImGuiTextBuffer@@@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$?TableSettingsHandler_ReadLine@@YAXPEAUImGuiContext@@PEAUImGuiSettingsHandler@@PEAXPEBD@Z DD imagerel ?TableSettingsHandler_ReadLine@@YAXPEAUImGuiContext@@PEAUImGuiSettingsHandler@@PEAXPEBD@Z
	DD	imagerel ?TableSettingsHandler_ReadLine@@YAXPEAUImGuiContext@@PEAUImGuiSettingsHandler@@PEAXPEBD@Z+144
	DD	imagerel $unwind$?TableSettingsHandler_ReadLine@@YAXPEAUImGuiContext@@PEAUImGuiSettingsHandler@@PEAXPEBD@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$0$?TableSettingsHandler_ReadLine@@YAXPEAUImGuiContext@@PEAUImGuiSettingsHandler@@PEAXPEBD@Z DD imagerel ?TableSettingsHandler_ReadLine@@YAXPEAUImGuiContext@@PEAUImGuiSettingsHandler@@PEAXPEBD@Z+144
	DD	imagerel ?TableSettingsHandler_ReadLine@@YAXPEAUImGuiContext@@PEAUImGuiSettingsHandler@@PEAXPEBD@Z+583
	DD	imagerel $chain$0$?TableSettingsHandler_ReadLine@@YAXPEAUImGuiContext@@PEAUImGuiSettingsHandler@@PEAXPEBD@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$1$?TableSettingsHandler_ReadLine@@YAXPEAUImGuiContext@@PEAUImGuiSettingsHandler@@PEAXPEBD@Z DD imagerel ?TableSettingsHandler_ReadLine@@YAXPEAUImGuiContext@@PEAUImGuiSettingsHandler@@PEAXPEBD@Z+583
	DD	imagerel ?TableSettingsHandler_ReadLine@@YAXPEAUImGuiContext@@PEAUImGuiSettingsHandler@@PEAXPEBD@Z+638
	DD	imagerel $chain$1$?TableSettingsHandler_ReadLine@@YAXPEAUImGuiContext@@PEAUImGuiSettingsHandler@@PEAXPEBD@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$?TableSettingsHandler_ReadOpen@@YAPEAXPEAUImGuiContext@@PEAUImGuiSettingsHandler@@PEBD@Z DD imagerel ?TableSettingsHandler_ReadOpen@@YAPEAXPEAUImGuiContext@@PEAUImGuiSettingsHandler@@PEBD@Z
	DD	imagerel ?TableSettingsHandler_ReadOpen@@YAPEAXPEAUImGuiContext@@PEAUImGuiSettingsHandler@@PEBD@Z+247
	DD	imagerel $unwind$?TableSettingsHandler_ReadOpen@@YAPEAXPEAUImGuiContext@@PEAUImGuiSettingsHandler@@PEBD@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$?TableSettingsCreate@ImGui@@YAPEAUImGuiTableSettings@@IH@Z DD imagerel $LN17@TableSetti
	DD	imagerel $LN17@TableSetti+175
	DD	imagerel $unwind$?TableSettingsCreate@ImGui@@YAPEAUImGuiTableSettings@@IH@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$?TableSettingsInit@@YAXPEAUImGuiTableSettings@@IHH@Z DD imagerel ?TableSettingsInit@@YAXPEAUImGuiTableSettings@@IHH@Z
	DD	imagerel ?TableSettingsInit@@YAXPEAUImGuiTableSettings@@IHH@Z+353
	DD	imagerel $unwind$?TableSettingsInit@@YAXPEAUImGuiTableSettings@@IHH@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$?TablePopBackgroundChannel@ImGui@@YAXXZ DD imagerel $LN12@TablePopBa
	DD	imagerel $LN12@TablePopBa+204
	DD	imagerel $unwind$?TablePopBackgroundChannel@ImGui@@YAXXZ
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$?TablePushBackgroundChannel@ImGui@@YAXXZ DD imagerel $LN10@TablePushB
	DD	imagerel $LN10@TablePushB+210
	DD	imagerel $unwind$?TablePushBackgroundChannel@ImGui@@YAXXZ
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$?ItemSize@ImGui@@YAXAEBUImRect@@M@Z DD imagerel $LN8@ItemSize
	DD	imagerel $LN8@ItemSize+50
	DD	imagerel $unwind$?ItemSize@ImGui@@YAXAEBUImRect@@M@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$?EndColumns@ImGui@@YAXXZ DD imagerel $LN146@EndColumns
	DD	imagerel $LN146@EndColumns+32
	DD	imagerel $unwind$?EndColumns@ImGui@@YAXXZ
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$3$?EndColumns@ImGui@@YAXXZ DD imagerel $LN146@EndColumns+32
	DD	imagerel $LN146@EndColumns+241
	DD	imagerel $chain$3$?EndColumns@ImGui@@YAXXZ
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$6$?EndColumns@ImGui@@YAXXZ DD imagerel $LN146@EndColumns+241
	DD	imagerel $LN146@EndColumns+300
	DD	imagerel $chain$6$?EndColumns@ImGui@@YAXXZ
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$13$?EndColumns@ImGui@@YAXXZ DD imagerel $LN146@EndColumns+300
	DD	imagerel $LN146@EndColumns+864
	DD	imagerel $chain$13$?EndColumns@ImGui@@YAXXZ
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$14$?EndColumns@ImGui@@YAXXZ DD imagerel $LN146@EndColumns+864
	DD	imagerel $LN146@EndColumns+1141
	DD	imagerel $chain$14$?EndColumns@ImGui@@YAXXZ
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$15$?EndColumns@ImGui@@YAXXZ DD imagerel $LN146@EndColumns+1141
	DD	imagerel $LN146@EndColumns+1166
	DD	imagerel $chain$15$?EndColumns@ImGui@@YAXXZ
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$16$?EndColumns@ImGui@@YAXXZ DD imagerel $LN146@EndColumns+1166
	DD	imagerel $LN146@EndColumns+1309
	DD	imagerel $chain$16$?EndColumns@ImGui@@YAXXZ
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$17$?EndColumns@ImGui@@YAXXZ DD imagerel $LN146@EndColumns+1309
	DD	imagerel $LN146@EndColumns+1375
	DD	imagerel $chain$17$?EndColumns@ImGui@@YAXXZ
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$?TableGcCompactSettings@ImGui@@YAXXZ DD imagerel $LN83@TableGcCom
	DD	imagerel $LN83@TableGcCom+492
	DD	imagerel $unwind$?TableGcCompactSettings@ImGui@@YAXXZ
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$?TableGcCompactTransientBuffers@ImGui@@YAXPEAUImGuiTable@@@Z DD imagerel $LN39@TableGcCom
	DD	imagerel $LN39@TableGcCom+295
	DD	imagerel $unwind$?TableGcCompactTransientBuffers@ImGui@@YAXPEAUImGuiTable@@@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$?TableGcCompactTransientBuffers@ImGui@@YAXPEAUImGuiTableTempData@@@Z DD imagerel $LN4@TableGcCom
	DD	imagerel $LN4@TableGcCom+31
	DD	imagerel $unwind$?TableGcCompactTransientBuffers@ImGui@@YAXPEAUImGuiTableTempData@@@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$?TableSettingsAddSettingsHandler@ImGui@@YAXXZ DD imagerel $LN28@TableSetti
	DD	imagerel $LN28@TableSetti+207
	DD	imagerel $unwind$?TableSettingsAddSettingsHandler@ImGui@@YAXXZ
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$?TableEndRow@ImGui@@YAXPEAUImGuiTable@@@Z DD imagerel $LN289@TableEndRo
	DD	imagerel $LN289@TableEndRo+37
	DD	imagerel $unwind$?TableEndRow@ImGui@@YAXPEAUImGuiTable@@@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$2$?TableEndRow@ImGui@@YAXPEAUImGuiTable@@@Z DD imagerel $LN289@TableEndRo+37
	DD	imagerel $LN289@TableEndRo+49
	DD	imagerel $chain$2$?TableEndRow@ImGui@@YAXPEAUImGuiTable@@@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$8$?TableEndRow@ImGui@@YAXPEAUImGuiTable@@@Z DD imagerel $LN289@TableEndRo+49
	DD	imagerel $LN289@TableEndRo+675
	DD	imagerel $chain$8$?TableEndRow@ImGui@@YAXPEAUImGuiTable@@@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$9$?TableEndRow@ImGui@@YAXPEAUImGuiTable@@@Z DD imagerel $LN289@TableEndRo+675
	DD	imagerel $LN289@TableEndRo+983
	DD	imagerel $chain$9$?TableEndRow@ImGui@@YAXPEAUImGuiTable@@@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$11$?TableEndRow@ImGui@@YAXPEAUImGuiTable@@@Z DD imagerel $LN289@TableEndRo+983
	DD	imagerel $LN289@TableEndRo+1174
	DD	imagerel $chain$11$?TableEndRow@ImGui@@YAXPEAUImGuiTable@@@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$12$?TableEndRow@ImGui@@YAXPEAUImGuiTable@@@Z DD imagerel $LN289@TableEndRo+1174
	DD	imagerel $LN289@TableEndRo+1414
	DD	imagerel $chain$12$?TableEndRow@ImGui@@YAXPEAUImGuiTable@@@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$13$?TableEndRow@ImGui@@YAXPEAUImGuiTable@@@Z DD imagerel $LN289@TableEndRo+1414
	DD	imagerel $LN289@TableEndRo+1672
	DD	imagerel $chain$13$?TableEndRow@ImGui@@YAXPEAUImGuiTable@@@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$14$?TableEndRow@ImGui@@YAXPEAUImGuiTable@@@Z DD imagerel $LN289@TableEndRo+1672
	DD	imagerel $LN289@TableEndRo+1733
	DD	imagerel $chain$14$?TableEndRow@ImGui@@YAXPEAUImGuiTable@@@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$15$?TableEndRow@ImGui@@YAXPEAUImGuiTable@@@Z DD imagerel $LN289@TableEndRo+1733
	DD	imagerel $LN289@TableEndRo+2149
	DD	imagerel $chain$15$?TableEndRow@ImGui@@YAXPEAUImGuiTable@@@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$16$?TableEndRow@ImGui@@YAXPEAUImGuiTable@@@Z DD imagerel $LN289@TableEndRo+2149
	DD	imagerel $LN289@TableEndRo+2177
	DD	imagerel $chain$16$?TableEndRow@ImGui@@YAXPEAUImGuiTable@@@Z
;	COMDAT xdata
xdata	SEGMENT
$chain$16$?TableEndRow@ImGui@@YAXPEAUImGuiTable@@@Z DD 021H
	DD	imagerel $LN289@TableEndRo
	DD	imagerel $LN289@TableEndRo+37
	DD	imagerel $unwind$?TableEndRow@ImGui@@YAXPEAUImGuiTable@@@Z
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$chain$15$?TableEndRow@ImGui@@YAXPEAUImGuiTable@@@Z DQ 00007b80000060021r ; 1.07342e-308
	DQ	00023c400001cd400r		; 5.4975e-308
	DD	imagerel $LN289@TableEndRo
	DD	imagerel $LN289@TableEndRo+37
	DD	imagerel $unwind$?TableEndRow@ImGui@@YAXPEAUImGuiTable@@@Z
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$chain$14$?TableEndRow@ImGui@@YAXPEAUImGuiTable@@@Z DQ 00007b80000020021r ; 1.07342e-308
	DD	imagerel $LN289@TableEndRo+37
	DD	imagerel $LN289@TableEndRo+49
	DD	imagerel $chain$2$?TableEndRow@ImGui@@YAXPEAUImGuiTable@@@Z
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$chain$13$?TableEndRow@ImGui@@YAXPEAUImGuiTable@@@Z DD 021H
	DD	imagerel $LN289@TableEndRo+49
	DD	imagerel $LN289@TableEndRo+675
	DD	imagerel $chain$8$?TableEndRow@ImGui@@YAXPEAUImGuiTable@@@Z
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$chain$12$?TableEndRow@ImGui@@YAXPEAUImGuiTable@@@Z DD 021H
	DD	imagerel $LN289@TableEndRo+675
	DD	imagerel $LN289@TableEndRo+983
	DD	imagerel $chain$9$?TableEndRow@ImGui@@YAXPEAUImGuiTable@@@Z
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$chain$11$?TableEndRow@ImGui@@YAXPEAUImGuiTable@@@Z DQ 0000b781400041421r ; 1.59497e-308
	DD	0c6808H
	DD	imagerel $LN289@TableEndRo+675
	DD	imagerel $LN289@TableEndRo+983
	DD	imagerel $chain$9$?TableEndRow@ImGui@@YAXPEAUImGuiTable@@@Z
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$chain$9$?TableEndRow@ImGui@@YAXPEAUImGuiTable@@@Z DQ 00009980900020921r ; 1.33419e-308
	DD	imagerel $LN289@TableEndRo+49
	DD	imagerel $LN289@TableEndRo+675
	DD	imagerel $chain$8$?TableEndRow@ImGui@@YAXPEAUImGuiTable@@@Z
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$chain$8$?TableEndRow@ImGui@@YAXPEAUImGuiTable@@@Z DQ 0001be440000c4021r ; 3.8788e-308
	DQ	00007b81b00216438r		; 1.07348e-308
	DQ	0000a88100008a815r		; 1.46458e-308
	DD	01af404H
	DD	imagerel $LN289@TableEndRo+37
	DD	imagerel $LN289@TableEndRo+49
	DD	imagerel $chain$2$?TableEndRow@ImGui@@YAXPEAUImGuiTable@@@Z
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$chain$2$?TableEndRow@ImGui@@YAXPEAUImGuiTable@@@Z DQ 0001cd40c00060c21r ; 4.00907e-308
	DQ	0002274040023c408r		; 5.13246e-308
	DD	imagerel $LN289@TableEndRo
	DD	imagerel $LN289@TableEndRo+37
	DD	imagerel $unwind$?TableEndRow@ImGui@@YAXPEAUImGuiTable@@@Z
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$?TableEndRow@ImGui@@YAXPEAUImGuiTable@@@Z DQ 0001d011000041e19r ; 4.03352e-308
	DD	050043005H
	DD	imagerel __GSHandlerCheck
	DD	068H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$?TableSettingsAddSettingsHandler@ImGui@@YAXXZ DQ 00000e20400010401r ; 1.22779e-309
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$?TableGcCompactTransientBuffers@ImGui@@YAXPEAUImGuiTableTempData@@@Z DQ 03002320600020601r ; 1.96423e-77
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$?TableGcCompactTransientBuffers@ImGui@@YAXPEAUImGuiTable@@@Z DQ 00007640f00060f01r ; 1.02782e-308
	DQ	0700b320f0006340fr		; 5.2777e+231
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$ip2state$?TableGcCompactSettings@ImGui@@YAXXZ DD 0202a104H
	DW	0435H
	DB	00H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$stateUnwindMap$?TableGcCompactSettings@ImGui@@YAXXZ DW 0a02H
	DD	imagerel ??1?$ImChunkStream@UImGuiTableSettings@@@@QEAA@XZ
	DB	040H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$cppxdata$?TableGcCompactSettings@ImGui@@YAXXZ DB 028H
	DD	imagerel $stateUnwindMap$?TableGcCompactSettings@ImGui@@YAXXZ
	DD	imagerel $ip2state$?TableGcCompactSettings@ImGui@@YAXXZ
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$?TableGcCompactSettings@ImGui@@YAXXZ DQ 00010641c000c2b19r ; 2.27946e-308
	DQ	0000e341c000f541cr		; 1.97525e-308
	DQ	0d014e016f018721cr		; -6.043e+77
	DD	07010c012H
	DD	imagerel __GSHandlerCheck_EH4
	DD	imagerel $cppxdata$?TableGcCompactSettings@ImGui@@YAXXZ
	DD	032H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$chain$17$?EndColumns@ImGui@@YAXXZ DD 021H
	DD	imagerel $LN146@EndColumns
	DD	imagerel $LN146@EndColumns+32
	DD	imagerel $unwind$?EndColumns@ImGui@@YAXXZ
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$chain$16$?EndColumns@ImGui@@YAXXZ DD 021H
	DD	imagerel $LN146@EndColumns+32
	DD	imagerel $LN146@EndColumns+241
	DD	imagerel $chain$3$?EndColumns@ImGui@@YAXXZ
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$chain$15$?EndColumns@ImGui@@YAXXZ DD 021H
	DD	imagerel $LN146@EndColumns+241
	DD	imagerel $LN146@EndColumns+300
	DD	imagerel $chain$6$?EndColumns@ImGui@@YAXXZ
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$chain$14$?EndColumns@ImGui@@YAXXZ DQ 00009a80000020021r ; 1.34287e-308
	DD	imagerel $LN146@EndColumns+241
	DD	imagerel $LN146@EndColumns+300
	DD	imagerel $chain$6$?EndColumns@ImGui@@YAXXZ
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$chain$13$?EndColumns@ImGui@@YAXXZ DQ 00008b847000e4721r ; 1.21264e-308
	DQ	0000d682c0009a835r		; 1.86446e-308
	DQ	0001de418001cf420r		; 4.15685e-308
	DQ	0001fc408001ed410r		; 4.41757e-308
	DD	imagerel $LN146@EndColumns+241
	DD	imagerel $LN146@EndColumns+300
	DD	imagerel $chain$6$?EndColumns@ImGui@@YAXXZ
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$chain$6$?EndColumns@ImGui@@YAXXZ DQ 0000a982300062321r ; 1.47332e-308
	DQ	00023540800207415r		; 5.37585e-308
	DD	imagerel $LN146@EndColumns+32
	DD	imagerel $LN146@EndColumns+241
	DD	imagerel $chain$3$?EndColumns@ImGui@@YAXXZ
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$chain$3$?EndColumns@ImGui@@YAXXZ DQ 0000b881e00081e21r ; 1.60368e-308
	DQ	000246408000c7819r		; 5.67136e-308
	DD	0223404H
	DD	imagerel $LN146@EndColumns
	DD	imagerel $LN146@EndColumns+32
	DD	imagerel $unwind$?EndColumns@ImGui@@YAXXZ
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$?EndColumns@ImGui@@YAXXZ DQ 00021010a00021919r ; 4.72941e-308
	DD	imagerel __GSHandlerCheck
	DD	078H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$?ItemSize@ImGui@@YAXAEBUImRect@@M@Z DQ 00000420400010401r ; 3.58617e-310
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$?TablePushBackgroundChannel@ImGui@@YAXXZ DQ 00000620400010401r ; 5.32451e-310
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$?TablePopBackgroundChannel@ImGui@@YAXXZ DQ 00000620400010401r ; 5.32451e-310
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$?TableSettingsInit@@YAXPEAUImGuiTableSettings@@IHH@Z DQ 00004741400081401r ; 6.19326e-309
	DQ	00002540a0003640fr		; 3.23787e-309
	DD	013405H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$?TableSettingsCreate@ImGui@@YAPEAUImGuiTableSettings@@IH@Z DQ 0000a6418000a1801r ; 1.44505e-308
	DQ	00008341800095418r		; 1.14084e-308
	DQ	07010e012f0143218r		; 6.5498e+231
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$?TableSettingsHandler_ReadOpen@@YAPEAXPEAUImGuiContext@@PEAUImGuiSettingsHandler@@PEBD@Z DQ 00006346100036119r ; 8.62857e-309
	DD	06204H
	DD	imagerel __GSHandlerCheck
	DD	028H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$chain$1$?TableSettingsHandler_ReadLine@@YAXPEAUImGuiContext@@PEAUImGuiSettingsHandler@@PEAXPEBD@Z DD 021H
	DD	imagerel ?TableSettingsHandler_ReadLine@@YAXPEAUImGuiContext@@PEAUImGuiSettingsHandler@@PEAXPEBD@Z
	DD	imagerel ?TableSettingsHandler_ReadLine@@YAXPEAUImGuiContext@@PEAUImGuiSettingsHandler@@PEAXPEBD@Z+144
	DD	imagerel $unwind$?TableSettingsHandler_ReadLine@@YAXPEAUImGuiContext@@PEAUImGuiSettingsHandler@@PEAXPEBD@Z
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$chain$0$?TableSettingsHandler_ReadLine@@YAXPEAUImGuiContext@@PEAUImGuiSettingsHandler@@PEAXPEBD@Z DQ 0000e340500020521r ; 1.9752e-308
	DD	imagerel ?TableSettingsHandler_ReadLine@@YAXPEAUImGuiContext@@PEAUImGuiSettingsHandler@@PEAXPEBD@Z
	DD	imagerel ?TableSettingsHandler_ReadLine@@YAXPEAUImGuiContext@@PEAUImGuiSettingsHandler@@PEAXPEBD@Z+144
	DD	imagerel $unwind$?TableSettingsHandler_ReadLine@@YAXPEAUImGuiContext@@PEAUImGuiSettingsHandler@@PEAXPEBD@Z
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$?TableSettingsHandler_ReadLine@@YAXPEAUImGuiContext@@PEAUImGuiSettingsHandler@@PEAXPEBD@Z DQ 07004920b00041919r ; 3.99201e+231
	DD	050026003H
	DD	imagerel __GSHandlerCheck
	DD	048H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$chain$8$?TableSettingsHandler_WriteAll@@YAXPEAUImGuiContext@@PEAUImGuiSettingsHandler@@PEAUImGuiTextBuffer@@@Z DD 021H
	DD	imagerel ?TableSettingsHandler_WriteAll@@YAXPEAUImGuiContext@@PEAUImGuiSettingsHandler@@PEAUImGuiTextBuffer@@@Z
	DD	imagerel ?TableSettingsHandler_WriteAll@@YAXPEAUImGuiContext@@PEAUImGuiSettingsHandler@@PEAUImGuiTextBuffer@@@Z+42
	DD	imagerel $unwind$?TableSettingsHandler_WriteAll@@YAXPEAUImGuiContext@@PEAUImGuiSettingsHandler@@PEAUImGuiTextBuffer@@@Z
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$chain$7$?TableSettingsHandler_WriteAll@@YAXPEAUImGuiContext@@PEAUImGuiSettingsHandler@@PEAUImGuiTextBuffer@@@Z DD 021H
	DD	imagerel ?TableSettingsHandler_WriteAll@@YAXPEAUImGuiContext@@PEAUImGuiSettingsHandler@@PEAUImGuiTextBuffer@@@Z+42
	DD	imagerel ?TableSettingsHandler_WriteAll@@YAXPEAUImGuiContext@@PEAUImGuiSettingsHandler@@PEAUImGuiTextBuffer@@@Z+59
	DD	imagerel $chain$0$?TableSettingsHandler_WriteAll@@YAXPEAUImGuiContext@@PEAUImGuiSettingsHandler@@PEAUImGuiTextBuffer@@@Z
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$chain$6$?TableSettingsHandler_WriteAll@@YAXPEAUImGuiContext@@PEAUImGuiSettingsHandler@@PEAUImGuiTextBuffer@@@Z DQ 00004681c000c1c21r ; 6.12824e-309
	DQ	0000be410000af417r		; 1.65363e-308
	DQ	0000e6408000cd40cr		; 2.00128e-308
	DD	0145404H
	DD	imagerel ?TableSettingsHandler_WriteAll@@YAXPEAUImGuiContext@@PEAUImGuiSettingsHandler@@PEAUImGuiTextBuffer@@@Z+42
	DD	imagerel ?TableSettingsHandler_WriteAll@@YAXPEAUImGuiContext@@PEAUImGuiSettingsHandler@@PEAUImGuiTextBuffer@@@Z+59
	DD	imagerel $chain$0$?TableSettingsHandler_WriteAll@@YAXPEAUImGuiContext@@PEAUImGuiSettingsHandler@@PEAUImGuiTextBuffer@@@Z
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$chain$0$?TableSettingsHandler_WriteAll@@YAXPEAUImGuiContext@@PEAUImGuiSettingsHandler@@PEAUImGuiTextBuffer@@@Z DQ 0000dc40400020421r ; 1.91435e-308
	DD	imagerel ?TableSettingsHandler_WriteAll@@YAXPEAUImGuiContext@@PEAUImGuiSettingsHandler@@PEAUImGuiTextBuffer@@@Z
	DD	imagerel ?TableSettingsHandler_WriteAll@@YAXPEAUImGuiContext@@PEAUImGuiSettingsHandler@@PEAUImGuiTextBuffer@@@Z+42
	DD	imagerel $unwind$?TableSettingsHandler_WriteAll@@YAXPEAUImGuiContext@@PEAUImGuiSettingsHandler@@PEAUImGuiTextBuffer@@@Z
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$?TableSettingsHandler_WriteAll@@YAXPEAUImGuiContext@@PEAUImGuiSettingsHandler@@PEAUImGuiTextBuffer@@@Z DQ 0700de21100031101r ; 5.79925e+231
	DD	0300cH
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$?SetWindowClipRectBeforeSetChannel@ImGui@@YAXPEAUImGuiWindow@@AEBUImRect@@@Z DQ 00000220400010401r ; 1.84783e-310
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$?SetColumnOffset@ImGui@@YAXHM@Z DQ 00003740f00060f01r ; 4.80248e-309
	DQ	0000134050002640ar		; 1.67326e-309
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$?PushColumnsBackground@ImGui@@YAXXZ DQ 00000620400010401r ; 5.32451e-310
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$?PopColumnsBackground@ImGui@@YAXXZ DQ 00000620400010401r ; 5.32451e-310
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$chain$1$?clear@?$ImVector@UImGuiTableColumnSortSpecs@@@@QEAAXXZ DD 021H
	DD	imagerel $LN21@clear
	DD	imagerel $LN21@clear+29
	DD	imagerel $unwind$?clear@?$ImVector@UImGuiTableColumnSortSpecs@@@@QEAAXXZ
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$chain$0$?clear@?$ImVector@UImGuiTableColumnSortSpecs@@@@QEAAXXZ DQ 00006740500020521r ; 8.97428e-309
	DD	imagerel $LN21@clear
	DD	imagerel $LN21@clear+29
	DD	imagerel $unwind$?clear@?$ImVector@UImGuiTableColumnSortSpecs@@@@QEAAXXZ
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$?clear@?$ImVector@UImGuiTableColumnSortSpecs@@@@QEAAXXZ DQ 03002320600020601r ; 1.96423e-77
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$?alloc_chunk@?$ImChunkStream@UImGuiTableSettings@@@@QEAAPEAUImGuiTableSettings@@_K@Z DQ 00008641400081401r ; 1.1669e-308
	DQ	00006341400075414r		; 8.62693e-309
	DD	070103214H
END
