; Listing generated by Microsoft (R) Optimizing Compiler Version 19.36.32534.0 

include listing.inc

INCLUDELIB OLDNAMES

;	COMDAT ?ScrolledAmount@?1??ProcessMouseWheel@Input@@SAXAEBUSDL_MouseWheelEvent@@@Z@4MA
_BSS	SEGMENT
?ScrolledAmount@?1??ProcessMouseWheel@Input@@SAXAEBUSDL_MouseWheelEvent@@@Z@4MA DD 01H DUP (?) ; `Input::ProcessMouseWheel'::`2'::ScrolledAmount
_BSS	ENDS
