; Listing generated by Microsoft (R) Optimizing Compiler Version 19.36.32535.0 

include listing.inc

INCLUDELIB OLDNAMES

PUBLIC	??$forward@V?$allocator@D@std@@@std@@YA$$QEAV?$allocator@D@0@AEAV10@@Z ; std::forward<std::allocator<char> >
PUBLIC	??$_Construct@$01PEBD@?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@AEAAXQEBD_K@Z ; std::basic_string<char,std::char_traits<char>,std::allocator<char> >::_Construct<2,char const *>
PUBLIC	??$?0V?$allocator@D@std@@$$V@?$_Compressed_pair@V?$allocator@D@std@@V?$_String_val@U?$_Simple_types@D@std@@@2@$00@std@@QEAA@U_One_then_variadic_args_t@1@$$QEAV?$allocator@D@1@@Z ; std::_Compressed_pair<std::allocator<char>,std::_String_val<std::_Simple_types<char> >,1>::_Compressed_pair<std::allocator<char>,std::_String_val<std::_Simple_types<char> >,1><std::allocator<char> >
PUBLIC	?select_on_container_copy_construction@?$_Default_allocator_traits@V?$allocator@D@std@@@std@@SA?AV?$allocator@D@2@AEBV32@@Z ; std::_Default_allocator_traits<std::allocator<char> >::select_on_container_copy_construction
PUBLIC	?_Myptr@?$_String_val@U?$_Simple_types@D@std@@@std@@QEBAPEBDXZ ; std::_String_val<std::_Simple_types<char> >::_Myptr
PUBLIC	??0?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@QEAA@AEBV01@@Z ; std::basic_string<char,std::char_traits<char>,std::allocator<char> >::basic_string<char,std::char_traits<char>,std::allocator<char> >
PUBLIC	??1Layer@@QEAA@XZ				; Layer::~Layer
PUBLIC	?GetName@Layer@@QEAA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@XZ ; Layer::GetName
PUBLIC	??0Layer@@QEAA@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@_K11U?$vec@$03M$0A@@glm@@@Z ; Layer::Layer
;	COMDAT pdata
pdata	SEGMENT
$pdata$??$_Construct@$01PEBD@?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@AEAAXQEBD_K@Z DD imagerel $LN78@Construct
	DD	imagerel $LN78@Construct+243
	DD	imagerel $unwind$??$_Construct@$01PEBD@?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@AEAAXQEBD_K@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$??0?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@QEAA@AEBV01@@Z DD imagerel $LN95@basic_stri
	DD	imagerel $LN95@basic_stri+277
	DD	imagerel $unwind$??0?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@QEAA@AEBV01@@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$??1Layer@@QEAA@XZ DD imagerel $LN42@Layer
	DD	imagerel $LN42@Layer+144
	DD	imagerel $unwind$??1Layer@@QEAA@XZ
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$?GetName@Layer@@QEAA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@XZ DD imagerel $LN7@GetName
	DD	imagerel $LN7@GetName+30
	DD	imagerel $unwind$?GetName@Layer@@QEAA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@XZ
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$??0Layer@@QEAA@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@_K11U?$vec@$03M$0A@@glm@@@Z DD imagerel $LN47@Layer
	DD	imagerel $LN47@Layer+315
	DD	imagerel $unwind$??0Layer@@QEAA@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@_K11U?$vec@$03M$0A@@glm@@@Z
;	COMDAT xdata
xdata	SEGMENT
$ip2state$??0Layer@@QEAA@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@_K11U?$vec@$03M$0A@@glm@@@Z DQ 0b0061c0438029008r ; -2.38676e-77
	DB	00H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$stateUnwindMap$??0Layer@@QEAA@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@_K11U?$vec@$03M$0A@@glm@@@Z DW 0c06H
	DD	imagerel ??1?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@QEAA@XZ
	DW	03450H
	DD	imagerel ??1Framebuffer@@QEAA@XZ
	DW	03640H
	DD	imagerel ?dtor$2@?0???0Layer@@QEAA@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@_K11U?$vec@$03M$0A@@glm@@@Z@4HA
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$cppxdata$??0Layer@@QEAA@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@_K11U?$vec@$03M$0A@@glm@@@Z DB 028H
	DD	imagerel $stateUnwindMap$??0Layer@@QEAA@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@_K11U?$vec@$03M$0A@@glm@@@Z
	DD	imagerel $ip2state$??0Layer@@QEAA@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@_K11U?$vec@$03M$0A@@glm@@@Z
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$??0Layer@@QEAA@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@_K11U?$vec@$03M$0A@@glm@@@Z DQ 00010341000081f19r ; 2.25336e-308
	DQ	07008e00af00c7210r		; 4.82739e+231
	DD	050066007H
	DD	imagerel __GSHandlerCheck_EH4
	DD	imagerel $cppxdata$??0Layer@@QEAA@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@_K11U?$vec@$03M$0A@@glm@@@Z
	DD	032H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$?GetName@Layer@@QEAA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@XZ DQ 03002520600020601r ; 1.97773e-77
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$ip2state$??1Layer@@QEAA@XZ DD 02c02ba06H
	DW	02004H
	DB	00H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$stateUnwindMap$??1Layer@@QEAA@XZ DW 0e04H
	DD	imagerel __std_terminate
	DB	02eH
	DD	imagerel __std_terminate
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$cppxdata$??1Layer@@QEAA@XZ DB 068H
	DD	imagerel $stateUnwindMap$??1Layer@@QEAA@XZ
	DD	imagerel $ip2state$??1Layer@@QEAA@XZ
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$??1Layer@@QEAA@XZ DQ 03002320600020619r	; 1.96423e-77
	DD	imagerel __CxxFrameHandler4
	DD	imagerel $cppxdata$??1Layer@@QEAA@XZ
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$??0?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@QEAA@AEBV01@@Z DQ 0000a340d00060d01r ; 1.41895e-308
	DQ	060067007e009320dr		; 3.76049e+154
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$??$_Construct@$01PEBD@?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@AEAAXQEBD_K@Z DQ 0000b340c00060c01r ; 1.55801e-308
	DQ	0500660077008320cr		; 3.23858e+77
END
