; Listing generated by Microsoft (R) Optimizing Compiler Version 19.36.32535.0 

include listing.inc

INCLUDELIB OLDNAMES

PUBLIC	?__autoclassinit2@Application@@QEAAX_K@Z	; Application::__autoclassinit2
PUBLIC	SDL_main
;	COMDAT pdata
pdata	SEGMENT
$pdata$SDL_main DD imagerel $LN18@SDL_main
	DD	imagerel $LN18@SDL_main+169
	DD	imagerel $unwind$SDL_main
;	COMDAT xdata
xdata	SEGMENT
$unwind$SDL_main DQ 00027010700021919r		; 6.3982e-308
	DD	imagerel __GSHandlerCheck
	DD	0120H
END
