; Listing generated by Microsoft (R) Optimizing Compiler Version 19.32.31332.0 

include listing.inc

INCLUDELIB OLDNAMES

PUBLIC	?m_MouseInCanvas@Mouse@Input@@2_NA		; Input::Mouse::m_MouseInCanvas
PUBLIC	?m_Color@WindowData@@2U?$vec@$03M$0A@@glm@@A	; WindowData::m_Color
;	COMDAT ?m_MouseInCanvas@Mouse@Input@@2_NA
_BSS	SEGMENT
?m_MouseInCanvas@Mouse@Input@@2_NA DB 01H DUP (?)	; Input::Mouse::m_MouseInCanvas
_BSS	ENDS
;	COMDAT ?dy@?1??FloodFill4Stack@PaintBucket@@QEAAXV?$shared_ptr@VLayer@@@std@@AEAVPixelBuffer@@@Z@4QBHB
CONST	SEGMENT
?dy@?1??FloodFill4Stack@PaintBucket@@QEAAXV?$shared_ptr@VLayer@@@std@@AEAVPixelBuffer@@@Z@4QBHB DD 0ffffffffH ; `PaintBucket::FloodFill4Stack'::`2'::dy
	DD	00H
	DD	01H
	DD	00H
CONST	ENDS
;	COMDAT ?PreviousPosition@?1??FloodFill4Stack@PaintBucket@@QEAAXV?$shared_ptr@VLayer@@@std@@AEAVPixelBuffer@@@Z@4U?$vec@$02M$0A@@glm@@A
_DATA	SEGMENT
?PreviousPosition@?1??FloodFill4Stack@PaintBucket@@QEAAXV?$shared_ptr@VLayer@@@std@@AEAVPixelBuffer@@@Z@4U?$vec@$02M$0A@@glm@@A DD 0bf800000r ; -1 ; `PaintBucket::FloodFill4Stack'::`2'::PreviousPosition
	DD	0bf800000r			; -1
	DD	0bf800000r			; -1
_DATA	ENDS
;	COMDAT ?m_Color@WindowData@@2U?$vec@$03M$0A@@glm@@A
_DATA	SEGMENT
?m_Color@WindowData@@2U?$vec@$03M$0A@@glm@@A DD 000000000r ; 0 ; WindowData::m_Color
	DD	000000000r			; 0
	DD	000000000r			; 0
	DD	03f800000r			; 1
_DATA	ENDS
;	COMDAT ?dx@?1??FloodFill4Stack@PaintBucket@@QEAAXV?$shared_ptr@VLayer@@@std@@AEAVPixelBuffer@@@Z@4QBHB
CONST	SEGMENT
?dx@?1??FloodFill4Stack@PaintBucket@@QEAAXV?$shared_ptr@VLayer@@@std@@AEAVPixelBuffer@@@Z@4QBHB DD 00H ; `PaintBucket::FloodFill4Stack'::`2'::dx
	DD	01H
	DD	00H
	DD	0ffffffffH
PUBLIC	??$construct_at@HHX@std@@YAPEAHQEAH$$QEAH@Z	; std::construct_at<int,int,void>
PUBLIC	??$construct@HH@?$_Default_allocator_traits@V?$allocator@H@std@@@std@@SAXAEAV?$allocator@H@1@QEAH$$QEAH@Z ; std::_Default_allocator_traits<std::allocator<int> >::construct<int,int>
PUBLIC	??$forward@H@std@@YA$$QEAHAEAH@Z		; std::forward<int>
PUBLIC	??$to_address@H@std@@YAPEAHQEAH@Z		; std::to_address<int>
PUBLIC	??$_Emplace_back@H@?$_Uninitialized_backout_al@V?$allocator@H@std@@@std@@QEAAX$$QEAH@Z ; std::_Uninitialized_backout_al<std::allocator<int> >::_Emplace_back<int>
PUBLIC	??$_To_address@PEAH@std@@YA?A_PAEBQEAH@Z	; std::_To_address<int *>
PUBLIC	??$_Copy_memmove@PEAHPEAH@std@@YAPEAHPEAH00@Z	; std::_Copy_memmove<int *,int *>
PUBLIC	??$_Voidify_iter@PEAH@std@@YAPEAXPEAH@Z		; std::_Voidify_iter<int *>
PUBLIC	??$construct_at@HAEBHX@std@@YAPEAHQEAHAEBH@Z	; std::construct_at<int,int const &,void>
PUBLIC	??$addressof@H@std@@YAPEAHAEAH@Z		; std::addressof<int>
PUBLIC	??0?$_Uninitialized_backout_al@V?$allocator@H@std@@@std@@QEAA@PEAHAEAV?$allocator@H@1@@Z ; std::_Uninitialized_backout_al<std::allocator<int> >::_Uninitialized_backout_al<std::allocator<int> >
PUBLIC	??1?$_Uninitialized_backout_al@V?$allocator@H@std@@@std@@QEAA@XZ ; std::_Uninitialized_backout_al<std::allocator<int> >::~_Uninitialized_backout_al<std::allocator<int> >
PUBLIC	?_Release@?$_Uninitialized_backout_al@V?$allocator@H@std@@@std@@QEAAPEAHXZ ; std::_Uninitialized_backout_al<std::allocator<int> >::_Release
PUBLIC	?__autoclassinit2@?$_Uninitialized_backout_al@V?$allocator@H@std@@@std@@QEAAX_K@Z ; std::_Uninitialized_backout_al<std::allocator<int> >::__autoclassinit2
PUBLIC	??$_Uninitialized_move@PEAHV?$allocator@H@std@@@std@@YAPEAHQEAH0PEAHAEAV?$allocator@H@0@@Z ; std::_Uninitialized_move<int *,std::allocator<int> >
PUBLIC	??$_Get_unwrapped@AEBQEAH@std@@YA?A_TAEBQEAH@Z	; std::_Get_unwrapped<int * const &>
PUBLIC	??$construct@HAEBH@?$_Default_allocator_traits@V?$allocator@H@std@@@std@@SAXAEAV?$allocator@H@1@QEAHAEBH@Z ; std::_Default_allocator_traits<std::allocator<int> >::construct<int,int const &>
PUBLIC	??$_Construct_in_place@HAEBH@std@@YAXAEAHAEBH@Z	; std::_Construct_in_place<int,int const &>
PUBLIC	??$forward@AEAPEAI@std@@YAAEAPEAIAEAPEAI@Z	; std::forward<unsigned int * &>
PUBLIC	??$?RAEBMAEBM@?$less@X@std@@QEBA_NAEBM0@Z	; std::less<void>::operator()<float const &,float const &>
PUBLIC	?_Get_first@?$_Compressed_pair@V?$allocator@H@std@@V?$_Vector_val@U?$_Simple_types@H@std@@@2@$00@std@@QEBAAEBV?$allocator@H@2@XZ ; std::_Compressed_pair<std::allocator<int>,std::_Vector_val<std::_Simple_types<int> >,1>::_Get_first
PUBLIC	?max_size@?$_Default_allocator_traits@V?$allocator@H@std@@@std@@SA_KAEBV?$allocator@H@2@@Z ; std::_Default_allocator_traits<std::allocator<int> >::max_size
PUBLIC	?capacity@?$vector@HV?$allocator@H@std@@@std@@QEBA_KXZ ; std::vector<int,std::allocator<int> >::capacity
PUBLIC	?_Getal@?$vector@HV?$allocator@H@std@@@std@@AEBAAEBV?$allocator@H@2@XZ ; std::vector<int,std::allocator<int> >::_Getal
PUBLIC	?allocate@?$allocator@H@std@@QEAAPEAH_K@Z	; std::allocator<int>::allocate
PUBLIC	?max_size@?$vector@HV?$allocator@H@std@@@std@@QEBA_KXZ ; std::vector<int,std::allocator<int> >::max_size
PUBLIC	?_Calculate_growth@?$vector@HV?$allocator@H@std@@@std@@AEBA_K_K@Z ; std::vector<int,std::allocator<int> >::_Calculate_growth
PUBLIC	?_Change_array@?$vector@HV?$allocator@H@std@@@std@@AEAAXQEAH_K1@Z ; std::vector<int,std::allocator<int> >::_Change_array
PUBLIC	?_Xlength@?$vector@HV?$allocator@H@std@@@std@@CAXXZ ; std::vector<int,std::allocator<int> >::_Xlength
PUBLIC	??$_Emplace_reallocate@AEBH@?$vector@HV?$allocator@H@std@@@std@@AEAAPEAHQEAHAEBH@Z ; std::vector<int,std::allocator<int> >::_Emplace_reallocate<int const &>
PUBLIC	??$_Emplace_back_with_unused_capacity@AEBH@?$vector@HV?$allocator@H@std@@@std@@AEAAAEAHAEBH@Z ; std::vector<int,std::allocator<int> >::_Emplace_back_with_unused_capacity<int const &>
PUBLIC	??$destroy_at@H@std@@YAXQEAH@Z			; std::destroy_at<int>
PUBLIC	??$?0AEAPEAI@?$_Compressed_pair@U?$default_delete@$$BY0A@I@std@@PEAI$00@std@@QEAA@U_Zero_then_variadic_args_t@1@AEAPEAI@Z ; std::_Compressed_pair<std::default_delete<unsigned int [0]>,unsigned int *,1>::_Compressed_pair<std::default_delete<unsigned int [0]>,unsigned int *,1><unsigned int * &>
PUBLIC	??$clamp@MU?$less@X@std@@@std@@YAAEBMAEBM00U?$less@X@0@@Z ; std::clamp<float,std::less<void> >
PUBLIC	??$move@AEAH@std@@YA$$QEAHAEAH@Z		; std::move<int &>
PUBLIC	??0?$allocator@H@std@@QEAA@XZ			; std::allocator<int>::allocator<int>
PUBLIC	??0?$_Vector_val@U?$_Simple_types@H@std@@@std@@QEAA@XZ ; std::_Vector_val<std::_Simple_types<int> >::_Vector_val<std::_Simple_types<int> >
PUBLIC	??$_Destroy_range@V?$allocator@H@std@@@std@@YAXPEAHQEAHAEAV?$allocator@H@0@@Z ; std::_Destroy_range<std::allocator<int> >
PUBLIC	??$?0$$V@?$_Compressed_pair@V?$allocator@H@std@@V?$_Vector_val@U?$_Simple_types@H@std@@@2@$00@std@@QEAA@U_Zero_then_variadic_args_t@1@@Z ; std::_Compressed_pair<std::allocator<int>,std::_Vector_val<std::_Simple_types<int> >,1>::_Compressed_pair<std::allocator<int>,std::_Vector_val<std::_Simple_types<int> >,1><>
PUBLIC	??$_Emplace_one_at_back@AEBH@?$vector@HV?$allocator@H@std@@@std@@AEAAAEAHAEBH@Z ; std::vector<int,std::allocator<int> >::_Emplace_one_at_back<int const &>
PUBLIC	??$forward@AEBH@std@@YAAEBHAEBH@Z		; std::forward<int const &>
PUBLIC	??$destroy@H@?$_Default_allocator_traits@V?$allocator@H@std@@@std@@SAXAEAV?$allocator@H@1@QEAH@Z ; std::_Default_allocator_traits<std::allocator<int> >::destroy<int>
PUBLIC	??$_Unfancy@H@std@@YAPEAHPEAH@Z			; std::_Unfancy<int>
PUBLIC	??$?RI$0A@@?$default_delete@$$BY0A@I@std@@QEBAXPEAI@Z ; std::default_delete<unsigned int [0]>::operator()<unsigned int,0>
PUBLIC	??$?0PEAIU?$default_delete@$$BY0A@I@std@@$0A@X@?$unique_ptr@$$BY0A@IU?$default_delete@$$BY0A@I@std@@@std@@QEAA@PEAI@Z ; std::unique_ptr<unsigned int [0],std::default_delete<unsigned int [0]> >::unique_ptr<unsigned int [0],std::default_delete<unsigned int [0]> ><unsigned int *,std::default_delete<unsigned int [0]>,0,void>
PUBLIC	??$?8M$0A@@glm@@YA_NAEBU?$vec@$02M$0A@@0@0@Z	; glm::operator==<float,0>
PUBLIC	??$clamp@M@std@@YAAEBMAEBM00@Z			; std::clamp<float>
PUBLIC	?deallocate@?$allocator@H@std@@QEAAXQEAH_K@Z	; std::allocator<int>::deallocate
PUBLIC	?_Get_first@?$_Compressed_pair@V?$allocator@H@std@@V?$_Vector_val@U?$_Simple_types@H@std@@@2@$00@std@@QEAAAEAV?$allocator@H@2@XZ ; std::_Compressed_pair<std::allocator<int>,std::_Vector_val<std::_Simple_types<int> >,1>::_Get_first
PUBLIC	?_Tidy@?$vector@HV?$allocator@H@std@@@std@@AEAAXXZ ; std::vector<int,std::allocator<int> >::_Tidy
PUBLIC	?_Orphan_range@?$vector@HV?$allocator@H@std@@@std@@AEBAXPEAH0@Z ; std::vector<int,std::allocator<int> >::_Orphan_range
PUBLIC	?_Getal@?$vector@HV?$allocator@H@std@@@std@@AEAAAEAV?$allocator@H@2@XZ ; std::vector<int,std::allocator<int> >::_Getal
PUBLIC	?_Get_first@?$_Compressed_pair@U?$default_delete@$$BY0A@I@std@@PEAI$00@std@@QEAAAEAU?$default_delete@$$BY0A@I@2@XZ ; std::_Compressed_pair<std::default_delete<unsigned int [0]>,unsigned int *,1>::_Get_first
PUBLIC	??0?$vector@HV?$allocator@H@std@@@std@@QEAA@XZ	; std::vector<int,std::allocator<int> >::vector<int,std::allocator<int> >
PUBLIC	??1?$vector@HV?$allocator@H@std@@@std@@QEAA@XZ	; std::vector<int,std::allocator<int> >::~vector<int,std::allocator<int> >
PUBLIC	??$emplace_back@AEBH@?$vector@HV?$allocator@H@std@@@std@@QEAA?A_TAEBH@Z ; std::vector<int,std::allocator<int> >::emplace_back<int const &>
PUBLIC	?push_back@?$vector@HV?$allocator@H@std@@@std@@QEAAXAEBH@Z ; std::vector<int,std::allocator<int> >::push_back
PUBLIC	?pop_back@?$vector@HV?$allocator@H@std@@@std@@QEAAXXZ ; std::vector<int,std::allocator<int> >::pop_back
PUBLIC	?size@?$vector@HV?$allocator@H@std@@@std@@QEBA_KXZ ; std::vector<int,std::allocator<int> >::size
PUBLIC	?back@?$vector@HV?$allocator@H@std@@@std@@QEAAAEAHXZ ; std::vector<int,std::allocator<int> >::back
PUBLIC	??1?$unique_ptr@$$BY0A@IU?$default_delete@$$BY0A@I@std@@@std@@QEAA@XZ ; std::unique_ptr<unsigned int [0],std::default_delete<unsigned int [0]> >::~unique_ptr<unsigned int [0],std::default_delete<unsigned int [0]> >
PUBLIC	??A?$unique_ptr@$$BY0A@IU?$default_delete@$$BY0A@I@std@@@std@@QEBAAEAI_K@Z ; std::unique_ptr<unsigned int [0],std::default_delete<unsigned int [0]> >::operator[]
PUBLIC	?get@?$unique_ptr@$$BY0A@IU?$default_delete@$$BY0A@I@std@@@std@@QEBAPEAIXZ ; std::unique_ptr<unsigned int [0],std::default_delete<unsigned int [0]> >::get
PUBLIC	?__autoclassinit2@?$vector@HV?$allocator@H@std@@@std@@QEAAX_K@Z ; std::vector<int,std::allocator<int> >::__autoclassinit2
PUBLIC	?__autoclassinit2@?$unique_ptr@$$BY0A@IU?$default_delete@$$BY0A@I@std@@@std@@QEAAX_K@Z ; std::unique_ptr<unsigned int [0],std::default_delete<unsigned int [0]> >::__autoclassinit2
PUBLIC	?FloodFill4Stack@PaintBucket@@QEAAXV?$shared_ptr@VLayer@@@std@@AEAVPixelBuffer@@@Z ; PaintBucket::FloodFill4Stack
PUBLIC	??1PaintBucket@@QEAA@XZ				; PaintBucket::~PaintBucket
PUBLIC	??0PaintBucket@@QEAA@XZ				; PaintBucket::PaintBucket
;	COMDAT pdata
pdata	SEGMENT
$pdata$??$_Copy_memmove@PEAHPEAH@std@@YAPEAHPEAH00@Z DD imagerel $LN4@Copy_memmo
	DD	imagerel $LN4@Copy_memmo+48
	DD	imagerel $unwind$??$_Copy_memmove@PEAHPEAH@std@@YAPEAHPEAH00@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$??$_Uninitialized_move@PEAHV?$allocator@H@std@@@std@@YAPEAHQEAH0PEAHAEAV?$allocator@H@0@@Z DD imagerel $LN23@Uninitiali
	DD	imagerel $LN23@Uninitiali+52
	DD	imagerel $unwind$??$_Uninitialized_move@PEAHV?$allocator@H@std@@@std@@YAPEAHQEAH0PEAHAEAV?$allocator@H@0@@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$?allocate@?$allocator@H@std@@QEAAPEAH_K@Z DD imagerel $LN32@allocate
	DD	imagerel $LN32@allocate+112
	DD	imagerel $unwind$?allocate@?$allocator@H@std@@QEAAPEAH_K@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$?_Change_array@?$vector@HV?$allocator@H@std@@@std@@AEAAXQEAH_K1@Z DD imagerel $LN27@Change_arr
	DD	imagerel $LN27@Change_arr+136
	DD	imagerel $unwind$?_Change_array@?$vector@HV?$allocator@H@std@@@std@@AEAAXQEAH_K1@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$?_Xlength@?$vector@HV?$allocator@H@std@@@std@@CAXXZ DD imagerel $LN4@Xlength
	DD	imagerel $LN4@Xlength+18
	DD	imagerel $unwind$?_Xlength@?$vector@HV?$allocator@H@std@@@std@@CAXXZ
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$??$_Emplace_reallocate@AEBH@?$vector@HV?$allocator@H@std@@@std@@AEAAPEAHQEAHAEBH@Z DD imagerel $LN141@Emplace_re
	DD	imagerel $LN141@Emplace_re+70
	DD	imagerel $unwind$??$_Emplace_reallocate@AEBH@?$vector@HV?$allocator@H@std@@@std@@AEAAPEAHQEAHAEBH@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$3$??$_Emplace_reallocate@AEBH@?$vector@HV?$allocator@H@std@@@std@@AEAAPEAHQEAHAEBH@Z DD imagerel $LN141@Emplace_re+70
	DD	imagerel $LN141@Emplace_re+391
	DD	imagerel $chain$3$??$_Emplace_reallocate@AEBH@?$vector@HV?$allocator@H@std@@@std@@AEAAPEAHQEAHAEBH@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$5$??$_Emplace_reallocate@AEBH@?$vector@HV?$allocator@H@std@@@std@@AEAAPEAHQEAHAEBH@Z DD imagerel $LN141@Emplace_re+391
	DD	imagerel $LN141@Emplace_re+398
	DD	imagerel $chain$5$??$_Emplace_reallocate@AEBH@?$vector@HV?$allocator@H@std@@@std@@AEAAPEAHQEAHAEBH@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$6$??$_Emplace_reallocate@AEBH@?$vector@HV?$allocator@H@std@@@std@@AEAAPEAHQEAHAEBH@Z DD imagerel $LN141@Emplace_re+398
	DD	imagerel $LN141@Emplace_re+404
	DD	imagerel $chain$6$??$_Emplace_reallocate@AEBH@?$vector@HV?$allocator@H@std@@@std@@AEAAPEAHQEAHAEBH@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$7$??$_Emplace_reallocate@AEBH@?$vector@HV?$allocator@H@std@@@std@@AEAAPEAHQEAHAEBH@Z DD imagerel $LN141@Emplace_re+404
	DD	imagerel $LN141@Emplace_re+410
	DD	imagerel $chain$7$??$_Emplace_reallocate@AEBH@?$vector@HV?$allocator@H@std@@@std@@AEAAPEAHQEAHAEBH@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$??$clamp@M@std@@YAAEBMAEBM00@Z DD imagerel $LN13@clamp
	DD	imagerel $LN13@clamp+79
	DD	imagerel $unwind$??$clamp@M@std@@YAAEBMAEBM00@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$?deallocate@?$allocator@H@std@@QEAAXQEAH_K@Z DD imagerel $LN23@deallocate
	DD	imagerel $LN23@deallocate+67
	DD	imagerel $unwind$?deallocate@?$allocator@H@std@@QEAAXQEAH_K@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$?_Tidy@?$vector@HV?$allocator@H@std@@@std@@AEAAXXZ DD imagerel $LN27@Tidy
	DD	imagerel $LN27@Tidy+92
	DD	imagerel $unwind$?_Tidy@?$vector@HV?$allocator@H@std@@@std@@AEAAXXZ
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$??1?$vector@HV?$allocator@H@std@@@std@@QEAA@XZ DD imagerel $LN30@vector
	DD	imagerel $LN30@vector+92
	DD	imagerel $unwind$??1?$vector@HV?$allocator@H@std@@@std@@QEAA@XZ
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$?FloodFill4Stack@PaintBucket@@QEAAXV?$shared_ptr@VLayer@@@std@@AEAVPixelBuffer@@@Z DD imagerel $LN318@FloodFill4
	DD	imagerel $LN318@FloodFill4+1246
	DD	imagerel $unwind$?FloodFill4Stack@PaintBucket@@QEAAXV?$shared_ptr@VLayer@@@std@@AEAVPixelBuffer@@@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$?GetColor@@YAIXZ DD imagerel ?GetColor@@YAIXZ
	DD	imagerel ?GetColor@@YAIXZ+201
	DD	imagerel $unwind$?GetColor@@YAIXZ
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$?push@@YAXAEAV?$vector@HV?$allocator@H@std@@@std@@HH@Z DD imagerel ?push@@YAXAEAV?$vector@HV?$allocator@H@std@@@std@@HH@Z
	DD	imagerel ?push@@YAXAEAV?$vector@HV?$allocator@H@std@@@std@@HH@Z+108
	DD	imagerel $unwind$?push@@YAXAEAV?$vector@HV?$allocator@H@std@@@std@@HH@Z
;	COMDAT xdata
xdata	SEGMENT
$unwind$?push@@YAXAEAV?$vector@HV?$allocator@H@std@@@std@@HH@Z DQ 00009341300041301r ; 1.27989e-308
	DD	0700f3213H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$?GetColor@@YAIXZ DQ 00000420400011319r	; 3.58617e-310
	DD	imagerel __GSHandlerCheck
	DD	010H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$ip2state$?FloodFill4Stack@PaintBucket@@QEAAXV?$shared_ptr@VLayer@@@std@@AEAVPixelBuffer@@@Z DQ 0051d047002044d0ar ; 4.87845e-284
	DD	0405bd06H
	DW	02a5H
	DB	00H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$stateUnwindMap$?FloodFill4Stack@PaintBucket@@QEAAXV?$shared_ptr@VLayer@@@std@@AEAVPixelBuffer@@@Z DW 0c06H
	DD	imagerel ??1?$shared_ptr@VLayer@@@std@@QEAA@XZ
	DW	03280H
	DD	imagerel ??1?$unique_ptr@$$BY0A@IU?$default_delete@$$BY0A@I@std@@@std@@QEAA@XZ
	DW	0201H
	DB	03aH
	DD	imagerel ??1?$vector@HV?$allocator@H@std@@@std@@QEAA@XZ
	DB	090H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$cppxdata$?FloodFill4Stack@PaintBucket@@QEAAXV?$shared_ptr@VLayer@@@std@@AEAVPixelBuffer@@@Z DB 028H
	DD	imagerel $stateUnwindMap$?FloodFill4Stack@PaintBucket@@QEAAXV?$shared_ptr@VLayer@@@std@@AEAVPixelBuffer@@@Z
	DD	imagerel $ip2state$?FloodFill4Stack@PaintBucket@@QEAAXV?$shared_ptr@VLayer@@@std@@AEAVPixelBuffer@@@Z
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$?FloodFill4Stack@PaintBucket@@QEAAXV?$shared_ptr@VLayer@@@std@@AEAVPixelBuffer@@@Z DQ 0000b982f00133d19r ; 1.61241e-308
	DQ	0000d7825000c882ar		; 1.87314e-308
	DQ	00026341d000e6821r		; 6.17557e-308
	DQ	0e010f012001e011dr		; -5.67746e+154
	DQ	06009700ac00cd00er		; 4.26329e+154
	DD	05008H
	DD	imagerel __GSHandlerCheck_EH4
	DD	imagerel $cppxdata$?FloodFill4Stack@PaintBucket@@QEAAXV?$shared_ptr@VLayer@@@std@@AEAVPixelBuffer@@@Z
	DD	0a2H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$??1?$vector@HV?$allocator@H@std@@@std@@QEAA@XZ DQ 03002320600020601r ; 1.96423e-77
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$?_Tidy@?$vector@HV?$allocator@H@std@@@std@@AEAAXXZ DQ 03002320600020601r ; 1.96423e-77
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$?deallocate@?$allocator@H@std@@QEAAXQEAH_K@Z DQ 00000420400010401r ; 3.58617e-310
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$??$clamp@M@std@@YAAEBMAEBM00@Z DQ 00000220400011219r ; 1.84783e-310
	DD	imagerel __GSHandlerCheck
	DD	00H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$chain$7$??$_Emplace_reallocate@AEBH@?$vector@HV?$allocator@H@std@@@std@@AEAAPEAHQEAHAEBH@Z DQ 00004e40000080021r ; 6.80125e-309
	DQ	0000664000005c400r		; 8.88726e-309
	DD	0e3400H
	DD	imagerel $LN141@Emplace_re
	DD	imagerel $LN141@Emplace_re+70
	DD	imagerel $unwind$??$_Emplace_reallocate@AEBH@?$vector@HV?$allocator@H@std@@@std@@AEAAPEAHQEAHAEBH@Z
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$chain$6$??$_Emplace_reallocate@AEBH@?$vector@HV?$allocator@H@std@@@std@@AEAAPEAHQEAHAEBH@Z DD 021H
	DD	imagerel $LN141@Emplace_re
	DD	imagerel $LN141@Emplace_re+70
	DD	imagerel $unwind$??$_Emplace_reallocate@AEBH@?$vector@HV?$allocator@H@std@@@std@@AEAAPEAHQEAHAEBH@Z
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$chain$5$??$_Emplace_reallocate@AEBH@?$vector@HV?$allocator@H@std@@@std@@AEAAPEAHQEAHAEBH@Z DQ 00004e40000080021r ; 6.80125e-309
	DQ	0000664000005c400r		; 8.88726e-309
	DD	0e3400H
	DD	imagerel $LN141@Emplace_re
	DD	imagerel $LN141@Emplace_re+70
	DD	imagerel $unwind$??$_Emplace_reallocate@AEBH@?$vector@HV?$allocator@H@std@@@std@@AEAAPEAHQEAHAEBH@Z
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$chain$3$??$_Emplace_reallocate@AEBH@?$vector@HV?$allocator@H@std@@@std@@AEAAPEAHQEAHAEBH@Z DQ 00004e42800082821r ; 6.8021e-309
	DQ	00006640e0005c416r		; 8.88755e-309
	DD	0e3405H
	DD	imagerel $LN141@Emplace_re
	DD	imagerel $LN141@Emplace_re+70
	DD	imagerel $unwind$??$_Emplace_reallocate@AEBH@?$vector@HV?$allocator@H@std@@@std@@AEAAPEAHQEAHAEBH@Z
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$??$_Emplace_reallocate@AEBH@?$vector@HV?$allocator@H@std@@@std@@AEAAPEAHQEAHAEBH@Z DQ 0f007620b00050b01r ; -4.53781e+231
	DQ	0000050027003d005r		; 4.34636e-310
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$?_Xlength@?$vector@HV?$allocator@H@std@@@std@@CAXXZ DQ 00000420400010401r ; 3.58617e-310
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$?_Change_array@?$vector@HV?$allocator@H@std@@@std@@AEAAXQEAH_K1@Z DQ 00009641400081401r ; 1.30597e-308
	DQ	00007341400085414r		; 1.00176e-308
	DD	070103214H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$?allocate@?$allocator@H@std@@QEAAPEAH_K@Z DQ 00000420400010401r ; 3.58617e-310
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$??$_Uninitialized_move@PEAHV?$allocator@H@std@@@std@@YAPEAHQEAH0PEAHAEAV?$allocator@H@0@@Z DQ 00009340a00040a01r ; 1.27987e-308
	DD	07006320aH
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$??$_Copy_memmove@PEAHPEAH@std@@YAPEAHPEAH00@Z DQ 00009340a00040a01r ; 1.27987e-308
	DD	07006320aH
END
