; Listing generated by Microsoft (R) Optimizing Compiler Version 19.36.32535.0 

include listing.inc

INCLUDELIB OLDNAMES

EXTRN	??_U@YAPEAX_K@Z:PROC				; operator new[]
EXTRN	??_V@YAXPEAX@Z:PROC				; operator delete[]
PUBLIC	?Init@PixelBuffer@@AEAAXXZ			; PixelBuffer::Init
PUBLIC	?Download@PixelBuffer@@QEAAXXZ			; PixelBuffer::Download
PUBLIC	??1PixelBuffer@@QEAA@XZ				; PixelBuffer::~PixelBuffer
PUBLIC	??0PixelBuffer@@QEAA@IHHH@Z			; PixelBuffer::PixelBuffer
;	COMDAT pdata
pdata	SEGMENT
$pdata$?Init@PixelBuffer@@AEAAXXZ DD imagerel $LN27@Init
	DD	imagerel $LN27@Init+170
	DD	imagerel $unwind$?Init@PixelBuffer@@AEAAXXZ
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$0$?Init@PixelBuffer@@AEAAXXZ DD imagerel $LN27@Init+170
	DD	imagerel $LN27@Init+238
	DD	imagerel $chain$0$?Init@PixelBuffer@@AEAAXXZ
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$1$?Init@PixelBuffer@@AEAAXXZ DD imagerel $LN27@Init+238
	DD	imagerel $LN27@Init+262
	DD	imagerel $chain$1$?Init@PixelBuffer@@AEAAXXZ
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$?Download@PixelBuffer@@QEAAXXZ DD imagerel $LN10@Download
	DD	imagerel $LN10@Download+196
	DD	imagerel $unwind$?Download@PixelBuffer@@QEAAXXZ
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$??1PixelBuffer@@QEAA@XZ DD imagerel $LN7@PixelBuffe
	DD	imagerel $LN7@PixelBuffe+35
	DD	imagerel $unwind$??1PixelBuffer@@QEAA@XZ
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$??0PixelBuffer@@QEAA@IHHH@Z DD imagerel $LN22@PixelBuffe
	DD	imagerel $LN22@PixelBuffe+112
	DD	imagerel $unwind$??0PixelBuffer@@QEAA@IHHH@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$0$??0PixelBuffer@@QEAA@IHHH@Z DD imagerel $LN22@PixelBuffe+112
	DD	imagerel $LN22@PixelBuffe+189
	DD	imagerel $chain$0$??0PixelBuffer@@QEAA@IHHH@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$1$??0PixelBuffer@@QEAA@IHHH@Z DD imagerel $LN22@PixelBuffe+189
	DD	imagerel $LN22@PixelBuffe+216
	DD	imagerel $chain$1$??0PixelBuffer@@QEAA@IHHH@Z
;	COMDAT xdata
xdata	SEGMENT
$chain$1$??0PixelBuffer@@QEAA@IHHH@Z DD 021H
	DD	imagerel $LN22@PixelBuffe
	DD	imagerel $LN22@PixelBuffe+112
	DD	imagerel $unwind$??0PixelBuffer@@QEAA@IHHH@Z
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$chain$0$??0PixelBuffer@@QEAA@IHHH@Z DQ 00006640500020521r ; 8.88736e-309
	DD	imagerel $LN22@PixelBuffe
	DD	imagerel $LN22@PixelBuffe+112
	DD	imagerel $unwind$??0PixelBuffer@@QEAA@IHHH@Z
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$??0PixelBuffer@@QEAA@IHHH@Z DQ 00007340a00040a01r ; 1.00174e-308
	DD	07006320aH
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$??1PixelBuffer@@QEAA@XZ DQ 03002320600020601r ; 1.96423e-77
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$?Download@PixelBuffer@@QEAAXXZ DQ 03002720600020601r ; 1.99122e-77
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$chain$1$?Init@PixelBuffer@@AEAAXXZ DD 021H
	DD	imagerel $LN27@Init
	DD	imagerel $LN27@Init+170
	DD	imagerel $unwind$?Init@PixelBuffer@@AEAAXXZ
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$chain$0$?Init@PixelBuffer@@AEAAXXZ DQ 00006640500020521r ; 8.88736e-309
	DD	imagerel $LN27@Init
	DD	imagerel $LN27@Init+170
	DD	imagerel $unwind$?Init@PixelBuffer@@AEAAXXZ
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$?Init@PixelBuffer@@AEAAXXZ DQ 00007340a00040a01r ; 1.00174e-308
	DD	07006320aH
END
