; Listing generated by Microsoft (R) Optimizing Compiler Version 19.36.32534.0 

include listing.inc

INCLUDELIB OLDNAMES

EXTRN	??_U@YAPEAX_K@Z:PROC				; operator new[]
EXTRN	??_V@YAXPEAX@Z:PROC				; operator delete[]
