; Listing generated by Microsoft (R) Optimizing Compiler Version 19.36.32535.0 

include listing.inc

INCLUDELIB OLDNAMES

PUBLIC	??_C@_0BA@HFDFHACB@Tool?5Properties@		; `string'
PUBLIC	??_C@_0BB@LAEBPEOJ@No?5tool?5selected@		; `string'
PUBLIC	??_C@_09KFCCKCGD@Move?5tool@			; `string'
PUBLIC	??_C@_0BC@DOONNDPC@Paint?5bucket?5tool@		; `string'
PUBLIC	??_C@_0BI@PENIANDP@Rectangular?5select?5tool@	; `string'
PUBLIC	??_C@_0BA@PNEKFLNG@Eyedropper?5tool@		; `string'
PUBLIC	??_C@_09LAHGKOJP@Crop?5tool@			; `string'
PUBLIC	??_C@_09DPJEAHJH@Text?5tool@			; `string'
PUBLIC	??_C@_07FGBMEDIO@Toolbar@			; `string'
PUBLIC	??_C@_07DJEMMAJP@No?5tool@			; `string'
PUBLIC	??_C@_03MBLNINKF@?n?$KC?$II@			; `string'
PUBLIC	??_C@_03OPKHDHD@?n?$KO?$LJ@			; `string'
PUBLIC	??_C@_03DDDELBAF@?n?$IO?$KO@			; `string'
PUBLIC	??_C@_03CIGAHOJ@?n?$IM?$KM@			; `string'
PUBLIC	??_C@_03BJBHBKOC@?n?$II?$LK@			; `string'
PUBLIC	??_C@_03CPKMAENC@?n?$IO?$LI@			; `string'
PUBLIC	??_C@_03EAALFKOJ@?n?$IJ?$IF@			; `string'
PUBLIC	??_C@_03HJPGKDFE@?n?$IO?$LO@			; `string'
PUBLIC	??_C@_03JDNEBBOI@?n?$IF?$KC@			; `string'
;	COMDAT ??_C@_03JDNEBBOI@?n?$IF?$KC@
CONST	SEGMENT
??_C@_03JDNEBBOI@?n?$IF?$KC@ DB 0eeH, 085H, 0a2H, 00H	; `string'
CONST	ENDS
;	COMDAT ??_C@_03HJPGKDFE@?n?$IO?$LO@
CONST	SEGMENT
??_C@_03HJPGKDFE@?n?$IO?$LO@ DB 0eeH, 08eH, 0beH, 00H	; `string'
CONST	ENDS
;	COMDAT ??_C@_03EAALFKOJ@?n?$IJ?$IF@
CONST	SEGMENT
??_C@_03EAALFKOJ@?n?$IJ?$IF@ DB 0eeH, 089H, 085H, 00H	; `string'
CONST	ENDS
;	COMDAT ??_C@_03CPKMAENC@?n?$IO?$LI@
CONST	SEGMENT
??_C@_03CPKMAENC@?n?$IO?$LI@ DB 0eeH, 08eH, 0b8H, 00H	; `string'
CONST	ENDS
;	COMDAT ??_C@_03BJBHBKOC@?n?$II?$LK@
CONST	SEGMENT
??_C@_03BJBHBKOC@?n?$II?$LK@ DB 0eeH, 088H, 0baH, 00H	; `string'
CONST	ENDS
;	COMDAT ??_C@_03CIGAHOJ@?n?$IM?$KM@
CONST	SEGMENT
??_C@_03CIGAHOJ@?n?$IM?$KM@ DB 0eeH, 08cH, 0acH, 00H	; `string'
CONST	ENDS
;	COMDAT ??_C@_03DDDELBAF@?n?$IO?$KO@
CONST	SEGMENT
??_C@_03DDDELBAF@?n?$IO?$KO@ DB 0eeH, 08eH, 0aeH, 00H	; `string'
CONST	ENDS
;	COMDAT ??_C@_03OPKHDHD@?n?$KO?$LJ@
CONST	SEGMENT
??_C@_03OPKHDHD@?n?$KO?$LJ@ DB 0eeH, 0aeH, 0b9H, 00H	; `string'
CONST	ENDS
;	COMDAT ??_C@_03MBLNINKF@?n?$KC?$II@
CONST	SEGMENT
??_C@_03MBLNINKF@?n?$KC?$II@ DB 0eeH, 0a2H, 088H, 00H	; `string'
CONST	ENDS
;	COMDAT ??_C@_07DJEMMAJP@No?5tool@
CONST	SEGMENT
??_C@_07DJEMMAJP@No?5tool@ DB 'No tool', 00H		; `string'
CONST	ENDS
;	COMDAT ??_C@_07FGBMEDIO@Toolbar@
CONST	SEGMENT
??_C@_07FGBMEDIO@Toolbar@ DB 'Toolbar', 00H		; `string'
CONST	ENDS
;	COMDAT ??_C@_09DPJEAHJH@Text?5tool@
CONST	SEGMENT
??_C@_09DPJEAHJH@Text?5tool@ DB 'Text tool', 00H	; `string'
CONST	ENDS
;	COMDAT ??_C@_09LAHGKOJP@Crop?5tool@
CONST	SEGMENT
??_C@_09LAHGKOJP@Crop?5tool@ DB 'Crop tool', 00H	; `string'
CONST	ENDS
;	COMDAT ??_C@_0BA@PNEKFLNG@Eyedropper?5tool@
CONST	SEGMENT
??_C@_0BA@PNEKFLNG@Eyedropper?5tool@ DB 'Eyedropper tool', 00H ; `string'
CONST	ENDS
;	COMDAT ??_C@_0BI@PENIANDP@Rectangular?5select?5tool@
CONST	SEGMENT
??_C@_0BI@PENIANDP@Rectangular?5select?5tool@ DB 'Rectangular select tool'
	DB	00H						; `string'
CONST	ENDS
;	COMDAT ??_C@_0BC@DOONNDPC@Paint?5bucket?5tool@
CONST	SEGMENT
??_C@_0BC@DOONNDPC@Paint?5bucket?5tool@ DB 'Paint bucket tool', 00H ; `string'
CONST	ENDS
;	COMDAT ??_C@_09KFCCKCGD@Move?5tool@
CONST	SEGMENT
??_C@_09KFCCKCGD@Move?5tool@ DB 'Move tool', 00H	; `string'
CONST	ENDS
;	COMDAT ??_C@_0BB@LAEBPEOJ@No?5tool?5selected@
CONST	SEGMENT
??_C@_0BB@LAEBPEOJ@No?5tool?5selected@ DB 'No tool selected', 00H ; `string'
CONST	ENDS
;	COMDAT ??_C@_0BA@HFDFHACB@Tool?5Properties@
CONST	SEGMENT
??_C@_0BA@HFDFHACB@Tool?5Properties@ DB 'Tool Properties', 00H ; `string'
PUBLIC	?ToolButton@Tools@@AEAAXW4Tool@@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@1@Z ; Tools::ToolButton
PUBLIC	?DrawToolbar@Tools@@QEAAXXZ			; Tools::DrawToolbar
PUBLIC	?DrawToolPropertiesMenu@Tools@@QEAAXXZ		; Tools::DrawToolPropertiesMenu
PUBLIC	??0Tools@@QEAA@XZ				; Tools::Tools
;	COMDAT pdata
pdata	SEGMENT
$pdata$?ToolButton@Tools@@AEAAXW4Tool@@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@1@Z DD imagerel $LN184@ToolButton
	DD	imagerel $LN184@ToolButton+898
	DD	imagerel $unwind$?ToolButton@Tools@@AEAAXW4Tool@@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@1@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$?DrawToolbar@Tools@@QEAAXXZ DD imagerel $LN48@DrawToolba
	DD	imagerel $LN48@DrawToolba+888
	DD	imagerel $unwind$?DrawToolbar@Tools@@QEAAXXZ
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$?DrawToolPropertiesMenu@Tools@@QEAAXXZ DD imagerel $LN53@DrawToolPr
	DD	imagerel $LN53@DrawToolPr+768
	DD	imagerel $unwind$?DrawToolPropertiesMenu@Tools@@QEAAXXZ
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$??0Tools@@QEAA@XZ DD imagerel $LN22@Tools
	DD	imagerel $LN22@Tools+112
	DD	imagerel $unwind$??0Tools@@QEAA@XZ
;	COMDAT xdata
xdata	SEGMENT
$unwind$??0Tools@@QEAA@XZ DQ 03002320600020601r	; 1.96423e-77
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$?DrawToolPropertiesMenu@Tools@@QEAAXXZ DQ 00015340d00051f19r ; 2.94869e-308
	DQ	0000070060012010dr		; 6.08546e-310
	DD	imagerel __GSHandlerCheck
	DD	080H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$ip2state$?DrawToolbar@Tools@@QEAAXXZ DQ 000220202fd00ca26r ; 5.0086e-308
	DQ	00022025c0022025cr		; 5.00898e-308
	DQ	00022025c0022025cr		; 5.00898e-308
	DQ	00022025c0022025cr		; 5.00898e-308
	DQ	00022025c0022025cr		; 5.00898e-308
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$stateUnwindMap$?DrawToolbar@Tools@@QEAAXXZ DW 0c02H
	DD	imagerel ??1?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@QEAA@XZ
	DW	0201H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$cppxdata$?DrawToolbar@Tools@@QEAAXXZ DB 028H
	DD	imagerel $stateUnwindMap$?DrawToolbar@Tools@@QEAAXXZ
	DD	imagerel $ip2state$?DrawToolbar@Tools@@QEAAXXZ
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$?DrawToolbar@Tools@@QEAAXXZ DQ 00013741200061211r ; 2.70533e-308
	DQ	0500bd21200123412r		; 4.02675e+77
	DD	imagerel __CxxFrameHandler4
	DD	imagerel $cppxdata$?DrawToolbar@Tools@@QEAAXXZ
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$ip2state$?ToolButton@Tools@@AEAAXW4Tool@@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@1@Z DQ 0027902095904d606r ; 9.55966e-297
	DB	00H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$stateUnwindMap$?ToolButton@Tools@@AEAAXW4Tool@@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@1@Z DW 0c04H
	DD	imagerel ??1?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@QEAA@XZ
	DW	03490H
	DD	imagerel ??1?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@QEAA@XZ
	DB	080H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$cppxdata$?ToolButton@Tools@@AEAAXW4Tool@@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@1@Z DB 028H
	DD	imagerel $stateUnwindMap$?ToolButton@Tools@@AEAAXW4Tool@@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@1@Z
	DD	imagerel $ip2state$?ToolButton@Tools@@AEAAXW4Tool@@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@1@Z
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$?ToolButton@Tools@@AEAAXW4Tool@@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@1@Z DQ 00006681000081f19r ; 8.90933e-309
	DQ	060047005e007d20br		; 3.42529e+154
	DD	030025003H
	DD	imagerel __GSHandlerCheck_EH4
	DD	imagerel $cppxdata$?ToolButton@Tools@@AEAAXW4Tool@@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@1@Z
	DD	052H
END
