; Listing generated by Microsoft (R) Optimizing Compiler Version 19.36.32534.0 

include listing.inc

INCLUDELIB OLDNAMES

PUBLIC	??_C@_0BA@HFDFHACB@Tool?5Properties@		; `string'
PUBLIC	??_C@_0BB@LAEBPEOJ@No?5tool?5selected@		; `string'
PUBLIC	??_C@_09KFCCKCGD@Move?5tool@			; `string'
PUBLIC	??_C@_0BC@DOONNDPC@Paint?5bucket?5tool@		; `string'
PUBLIC	??_C@_0BI@PENIANDP@Rectangular?5select?5tool@	; `string'
PUBLIC	??_C@_0BA@PNEKFLNG@Eyedropper?5tool@		; `string'
PUBLIC	??_C@_09LAHGKOJP@Crop?5tool@			; `string'
PUBLIC	??_C@_09DPJEAHJH@Text?5tool@			; `string'
PUBLIC	??_C@_07FGBMEDIO@Toolbar@			; `string'
PUBLIC	??_C@_07DJEMMAJP@No?5tool@			; `string'
PUBLIC	??_C@_03MBLNINKF@?n?$KC?$II@			; `string'
PUBLIC	??_C@_03OPKHDHD@?n?$KO?$LJ@			; `string'
PUBLIC	??_C@_03DDDELBAF@?n?$IO?$KO@			; `string'
PUBLIC	??_C@_03CIGAHOJ@?n?$IM?$KM@			; `string'
PUBLIC	??_C@_03BJBHBKOC@?n?$II?$LK@			; `string'
PUBLIC	??_C@_03CPKMAENC@?n?$IO?$LI@			; `string'
PUBLIC	??_C@_03EAALFKOJ@?n?$IJ?$IF@			; `string'
PUBLIC	??_C@_03HJPGKDFE@?n?$IO?$LO@			; `string'
PUBLIC	??_C@_03JDNEBBOI@?n?$IF?$KC@			; `string'
;	COMDAT ??_C@_03JDNEBBOI@?n?$IF?$KC@
CONST	SEGMENT
??_C@_03JDNEBBOI@?n?$IF?$KC@ DB 0eeH, 085H, 0a2H, 00H	; `string'
CONST	ENDS
;	COMDAT ??_C@_03HJPGKDFE@?n?$IO?$LO@
CONST	SEGMENT
??_C@_03HJPGKDFE@?n?$IO?$LO@ DB 0eeH, 08eH, 0beH, 00H	; `string'
CONST	ENDS
;	COMDAT ??_C@_03EAALFKOJ@?n?$IJ?$IF@
CONST	SEGMENT
??_C@_03EAALFKOJ@?n?$IJ?$IF@ DB 0eeH, 089H, 085H, 00H	; `string'
CONST	ENDS
;	COMDAT ??_C@_03CPKMAENC@?n?$IO?$LI@
CONST	SEGMENT
??_C@_03CPKMAENC@?n?$IO?$LI@ DB 0eeH, 08eH, 0b8H, 00H	; `string'
CONST	ENDS
;	COMDAT ??_C@_03BJBHBKOC@?n?$II?$LK@
CONST	SEGMENT
??_C@_03BJBHBKOC@?n?$II?$LK@ DB 0eeH, 088H, 0baH, 00H	; `string'
CONST	ENDS
;	COMDAT ??_C@_03CIGAHOJ@?n?$IM?$KM@
CONST	SEGMENT
??_C@_03CIGAHOJ@?n?$IM?$KM@ DB 0eeH, 08cH, 0acH, 00H	; `string'
CONST	ENDS
;	COMDAT ??_C@_03DDDELBAF@?n?$IO?$KO@
CONST	SEGMENT
??_C@_03DDDELBAF@?n?$IO?$KO@ DB 0eeH, 08eH, 0aeH, 00H	; `string'
CONST	ENDS
;	COMDAT ??_C@_03OPKHDHD@?n?$KO?$LJ@
CONST	SEGMENT
??_C@_03OPKHDHD@?n?$KO?$LJ@ DB 0eeH, 0aeH, 0b9H, 00H	; `string'
CONST	ENDS
;	COMDAT ??_C@_03MBLNINKF@?n?$KC?$II@
CONST	SEGMENT
??_C@_03MBLNINKF@?n?$KC?$II@ DB 0eeH, 0a2H, 088H, 00H	; `string'
CONST	ENDS
;	COMDAT ??_C@_07DJEMMAJP@No?5tool@
CONST	SEGMENT
??_C@_07DJEMMAJP@No?5tool@ DB 'No tool', 00H		; `string'
CONST	ENDS
;	COMDAT ??_C@_07FGBMEDIO@Toolbar@
CONST	SEGMENT
??_C@_07FGBMEDIO@Toolbar@ DB 'Toolbar', 00H		; `string'
CONST	ENDS
;	COMDAT ??_C@_09DPJEAHJH@Text?5tool@
CONST	SEGMENT
??_C@_09DPJEAHJH@Text?5tool@ DB 'Text tool', 00H	; `string'
CONST	ENDS
;	COMDAT ??_C@_09LAHGKOJP@Crop?5tool@
CONST	SEGMENT
??_C@_09LAHGKOJP@Crop?5tool@ DB 'Crop tool', 00H	; `string'
CONST	ENDS
;	COMDAT ??_C@_0BA@PNEKFLNG@Eyedropper?5tool@
CONST	SEGMENT
??_C@_0BA@PNEKFLNG@Eyedropper?5tool@ DB 'Eyedropper tool', 00H ; `string'
CONST	ENDS
;	COMDAT ??_C@_0BI@PENIANDP@Rectangular?5select?5tool@
CONST	SEGMENT
??_C@_0BI@PENIANDP@Rectangular?5select?5tool@ DB 'Rectangular select tool'
	DB	00H						; `string'
CONST	ENDS
;	COMDAT ??_C@_0BC@DOONNDPC@Paint?5bucket?5tool@
CONST	SEGMENT
??_C@_0BC@DOONNDPC@Paint?5bucket?5tool@ DB 'Paint bucket tool', 00H ; `string'
CONST	ENDS
;	COMDAT ??_C@_09KFCCKCGD@Move?5tool@
CONST	SEGMENT
??_C@_09KFCCKCGD@Move?5tool@ DB 'Move tool', 00H	; `string'
CONST	ENDS
;	COMDAT ??_C@_0BB@LAEBPEOJ@No?5tool?5selected@
CONST	SEGMENT
??_C@_0BB@LAEBPEOJ@No?5tool?5selected@ DB 'No tool selected', 00H ; `string'
CONST	ENDS
;	COMDAT ??_C@_0BA@HFDFHACB@Tool?5Properties@
CONST	SEGMENT
??_C@_0BA@HFDFHACB@Tool?5Properties@ DB 'Tool Properties', 00H ; `string'
